#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/accessible/tests/mochitest/attributes
VPATH		= /home/txema/work/firefox-20.0+build1/accessible/tests/mochitest/attributes
relativesrcdir  = accessible/attributes

include $(DEPTH)/config/autoconf.mk

MOCHITEST_A11Y_FILES =\
		test_obj.html \
		test_obj_css.html \
		test_obj_css.xul \
		test_obj_group.html \
		test_obj_group.xul \
		test_obj_group_tree.xul \
		test_tag.html \
		test_text.html \
		test_xml-roles.html \
		$(NULL)

include $(topsrcdir)/config/rules.mk
