#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/toolkit/components/passwordmgr/test/browser
VPATH		= /home/txema/work/firefox-20.0+build1/toolkit/components/passwordmgr/test/browser
relativesrcdir  = toolkit/components/passwordmgr/test/browser

include $(DEPTH)/config/autoconf.mk

MOCHITEST_BROWSER_FILES = \
  browser_passwordmgrdlg.js \
  browser_passwordmgr_sort.js \
  browser_passwordmgrcopypwd.js \
  browser_passwordmgr_observers.js \
  $(NULL)

include $(topsrcdir)/config/rules.mk
