dom_quickstubs.cpp: \
		../../../dist/idl/nsIDOMWindow.idl \
		../../../dist/idl/nsIDOMWindow.idl \
		../../../dist/idl/nsIDOMJSWindow.idl \
		../../../dist/idl/nsIDOMScreen.idl \
		../../../dist/idl/nsIDOMClientRect.idl \
		../../../dist/idl/nsIDOMPaintRequest.idl \
		../../../dist/idl/nsIDOMCanvasRenderingContext2D.idl \
		../../../dist/idl/nsIDOMCanvasRenderingContext2D.idl \
		../../../dist/idl/nsIDOMCanvasRenderingContext2D.idl \
		../../../dist/idl/nsIDOMCharacterData.idl \
		../../../dist/idl/nsIDOMDocument.idl \
		../../../dist/idl/nsIDOMElement.idl \
		../../../dist/idl/nsIDOMNamedNodeMap.idl \
		../../../dist/idl/nsIDOMText.idl \
		../../../dist/idl/nsIDOMDOMStringList.idl \
		../../../dist/idl/nsIDOMXULDocument.idl \
		../../../dist/idl/nsIDOMElementCSSInlineStyle.idl \
		../../../dist/idl/nsIDOMRect.idl \
		../../../dist/idl/nsIDOMEventTarget.idl \
		../../../dist/idl/nsIDOMEvent.idl \
		../../../dist/idl/nsIDOMMouseEvent.idl \
		../../../dist/idl/nsIDOMKeyEvent.idl \
		../../../dist/idl/nsIDOMMutationEvent.idl \
		../../../dist/idl/nsIDOMDragEvent.idl \
		../../../dist/idl/nsIDOMScrollAreaEvent.idl \
		../../../dist/idl/nsIDOMNotifyPaintEvent.idl \
		../../../dist/idl/nsIDOMMessageEvent.idl \
		../../../dist/idl/nsIDOMMouseScrollEvent.idl \
		../../../dist/idl/nsIDOMProgressEvent.idl \
		../../../dist/idl/nsIDOMUIEvent.idl \
		../../../dist/idl/nsIDOMTouchEvent.idl \
		../../../dist/idl/nsIDOMTouchEvent.idl \
		../../../dist/idl/nsIDOMTouchEvent.idl \
		../../../dist/idl/nsIDOMHTMLBaseElement.idl \
		../../../dist/idl/nsIDOMHTMLButtonElement.idl \
		../../../dist/idl/nsIDOMHTMLCommandElement.idl \
		../../../dist/idl/nsIDOMHTMLFormElement.idl \
		../../../dist/idl/nsIDOMHTMLFrameElement.idl \
		../../../dist/idl/nsIDOMHTMLIFrameElement.idl \
		../../../dist/idl/nsIDOMHTMLInputElement.idl \
		../../../dist/idl/nsIDOMHTMLLinkElement.idl \
		../../../dist/idl/nsIDOMHTMLMeterElement.idl \
		../../../dist/idl/nsIDOMHTMLMenuElement.idl \
		../../../dist/idl/nsIDOMHTMLMenuItemElement.idl \
		../../../dist/idl/nsIDOMHTMLOptionElement.idl \
		../../../dist/idl/nsIDOMHTMLProgressElement.idl \
		../../../dist/idl/nsIDOMHTMLSelectElement.idl \
		../../../dist/idl/nsIDOMHTMLStyleElement.idl \
		../../../dist/idl/nsIDOMHTMLTextAreaElement.idl \
		../../../dist/idl/nsIDOMHTMLTitleElement.idl \
		../../../dist/idl/nsIDOMHTMLCanvasElement.idl \
		../../../dist/idl/nsIDOMRange.idl \
		../../../dist/idl/nsIDOMToString.idl \
		../../../dist/idl/nsIDOMStorage.idl \
		../../../dist/idl/nsIDOMStorageItem.idl \
		../../../dist/idl/nsIDOMNodeIterator.idl \
		../../../dist/idl/nsIDOMXPathExpression.idl \
		../../../dist/idl/nsIDOMXPathNSResolver.idl \
		../../../dist/idl/nsIDOMXPathResult.idl \
		../../../dist/idl/nsIDOMNSXPathExpression.idl \
		../../../dist/idl/nsIDOMXULElement.idl \
		../../../dist/idl/nsIBoxObject.idl \
		../../../dist/idl/nsIDOMFileReader.idl \
		../../../dist/idl/nsIDOMNotifyAudioAvailableEvent.idl \
		../../../dist/idl/nsIDOMHTMLAudioElement.idl \
		../../../dist/idl/nsIIDBCursor.idl \
		../../../dist/idl/nsIIDBCursorWithValue.idl \
		../../../dist/idl/nsIIDBDatabase.idl \
		../../../dist/idl/nsIIDBFactory.idl \
		../../../dist/idl/nsIIDBFileHandle.idl \
		../../../dist/idl/nsIIDBIndex.idl \
		../../../dist/idl/nsIIDBKeyRange.idl \
		../../../dist/idl/nsIIDBObjectStore.idl \
		../../../dist/idl/nsIIDBRequest.idl \
		../../../dist/idl/nsIIDBTransaction.idl \
		../../../dist/idl/nsIIDBOpenDBRequest.idl \
		../../../dist/idl/nsIIDBVersionChangeEvent.idl \
		../../../dist/idl/nsIIndexedDatabaseManager.idl \
		../../../dist/idl/nsIIndexedDatabaseManager.idl \
		../../../dist/idl/nsIDOMDOMError.idl \
		../../../dist/idl/nsIDOMFileHandle.idl \
		../../../dist/idl/nsIDOMFileRequest.idl \
		../../../dist/idl/nsIDOMLockedFile.idl \
		../../../dist/idl/nsIDOMNode.idl \
		../../../dist/idl/nsIDOMSVGElement.idl \
		../../../dist/idl/nsIDOMHTMLDocument.idl \
		../../../dist/idl/nsIDOMHTMLElement.idl

