#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/jquery/test
VPATH		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/jquery/test
relativesrcdir	= dom/tests/mochitest/ajax/jquery/test

include $(DEPTH)/config/autoconf.mk

DIRS	= \
	data \
	unit \
	$(NULL)

MOCHITEST_FILES	= \
	index.html \
	offset.html \
	test.js \
	fix.html \
	$(NULL)

include $(topsrcdir)/config/rules.mk
