#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/dom/src/jsurl/test
VPATH		= /home/txema/work/firefox-20.0+build1/dom/src/jsurl/test
relativesrcdir  = dom/src/jsurl/test

include $(DEPTH)/config/autoconf.mk

MOCHITEST_FILES = 	pass.html \
		fail.html \
		test_bug351633-1.html \
		form-submit.html \
		test_bug351633-2.html \
		load-stopping-1a.html \
		load-stopping-1b.html \
		load-stopping-1c.html \
		load-stopping-1d.html \
		test_bug351633-3.html \
		test_bug351633-4.html \
		test_bug384981.html \
		$(NULL)

include $(topsrcdir)/config/rules.mk
