# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH     = ../../../..
topsrcdir = /home/txema/work/firefox-20.0+build1
srcdir    = /home/txema/work/firefox-20.0+build1/toolkit/components/microformats/tests
VPATH     = /home/txema/work/firefox-20.0+build1/toolkit/components/microformats/tests

include $(DEPTH)/config/autoconf.mk

MOCHITEST_FILES = \
		test_Microformats.html \
		test_Microformats_hCard.html \
		test_Microformats_geo.html \
		test_Microformats_hCalendar.html \
		test_Microformats_adr.html \
		test_Microformats_count.html \
		test_Microformats_getters.html \
		test_Microformats_negative.html \
		test_Microformats_add.html \
		test_framerecursion.html \
		geo.html \
		$(NULL)

include $(topsrcdir)/config/rules.mk
