# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/accessible/tests/mochitest/role
VPATH		= /home/txema/work/firefox-20.0+build1/accessible/tests/mochitest/role
relativesrcdir  = accessible/role

include $(DEPTH)/config/autoconf.mk

MOCHITEST_A11Y_FILES =\
		test_aria.html \
		test_aria.xul \
		test_general.html \
		test_svg.html \
		$(NULL)

include $(topsrcdir)/config/rules.mk
