#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../../../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/prototype/test/unit/tmp
VPATH		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/prototype/test/unit/tmp
relativesrcdir	= dom/tests/mochitest/ajax/prototype/test/unit/tmp

include $(DEPTH)/config/autoconf.mk

MOCHITEST_FILES= \
	ajax_test.html \
	array_test.html \
	base_test.html \
	dom_test.html \
	element_mixins_test.html \
	enumerable_test.html \
	event_test.html \
	form_test.html \
	hash_test.html \
	number_test.html \
	position_test.html \
	range_test.html \
	selector_test.html \
	string_test.html \
	unit_test.html \
	$(NULL)

include $(topsrcdir)/config/rules.mk
