#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/jquery/test/data
VPATH		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/jquery/test/data
relativesrcdir	= dom/tests/mochitest/ajax/jquery/test/data

include $(DEPTH)/config/autoconf.mk

DIRS	= \
	offset \
	$(NULL)

MOCHITEST_FILES	= \
	cow.jpg \
	dashboard.xml \
	iframe.html \
	json_assigned_obj.js \
	json_obj.js \
	name.html \
	test.html \
	test.js \
	test2.html \
	test3.html \
	testrunner.js \
	testsuite.css \
	with_fries.xml \
	$(NULL)

include $(topsrcdir)/config/rules.mk
