# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH          = ../../..
topsrcdir      = /home/txema/work/firefox-20.0+build1
srcdir         = /home/txema/work/firefox-20.0+build1/webapprt/test/content
VPATH          = /home/txema/work/firefox-20.0+build1/webapprt/test/content
relativesrcdir = webapprt/test/content

include $(DEPTH)/config/autoconf.mk

MOCHITEST_FILES = \
  test.webapp \
  webapprt_sample.html \
  $(NULL)

include $(topsrcdir)/config/rules.mk
