# Generated automatically from Makefile.in by configure.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

#! gmake

MOD_DEPTH	= ..
topsrcdir	= /home/txema/work/firefox-20.0+build1/nsprpub
srcdir		= /home/txema/work/firefox-20.0+build1/nsprpub/pr
VPATH		= /home/txema/work/firefox-20.0+build1/nsprpub/pr

include $(MOD_DEPTH)/config/autoconf.mk

DIRS = include src

include $(topsrcdir)/config/rules.mk
