#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/rdf/base/idl
VPATH		= /home/txema/work/firefox-20.0+build1/rdf/base/idl

include $(DEPTH)/config/autoconf.mk

MODULE		= rdf
GRE_MODULE	= 1

XPIDLSRCS	= \
		rdfIDataSource.idl \
		rdfITripleVisitor.idl \
		rdfISerializer.idl \
		nsIRDFCompositeDataSource.idl \
		nsIRDFContainer.idl \
		nsIRDFContainerUtils.idl \
		nsIRDFDelegateFactory.idl \
		nsIRDFDataSource.idl \
		nsIRDFLiteral.idl \
		nsIRDFNode.idl \
		nsIRDFObserver.idl \
		nsIRDFInMemoryDataSource.idl \
		nsIRDFPropagatableDataSource.idl \
		nsIRDFPurgeableDataSource.idl \
		nsIRDFRemoteDataSource.idl \
		nsIRDFResource.idl \
		nsIRDFService.idl \
		nsIRDFXMLParser.idl \
		nsIRDFXMLSerializer.idl \
		nsIRDFXMLSink.idl \
		nsIRDFXMLSource.idl \
		nsIRDFInferDataSource.idl \
		$(NULL)

include $(topsrcdir)/config/rules.mk

