#!/bin/sh

set -e

TESTSUITE_DIR=/$($(dirname $0)/../rules echo-MOZ_TESTDIR 2>/dev/null)
TESTRESULTS_DIR=${ADTRESULTSDIR:-"/tmp/testresults"}

export LC_ALL=en_US.UTF-8

mkdir -p $TESTRESULTS_DIR
$TESTSUITE_DIR/run_xpcshell_tests --own-display --own-session-bus --xunit-file $TESTRESULTS_DIR/xpcshell-package-tests.xml --xunit-suite-name "xpcshell.package" --manifest $TESTSUITE_DIR/xpcshell/package-tests/xpcshell.ini
