#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH     = ../../..
topsrcdir = /home/txema/work/firefox-20.0+build1
srcdir    = /home/txema/work/firefox-20.0+build1/toolkit/mozapps/preferences
VPATH     = /home/txema/work/firefox-20.0+build1/toolkit/mozapps/preferences

include $(topsrcdir)/config/config.mk

# Need to make the jar here

include $(topsrcdir)/config/rules.mk
