#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/accessible/tests/mochitest/actions
VPATH		= /home/txema/work/firefox-20.0+build1/accessible/tests/mochitest/actions
relativesrcdir  = accessible/actions

include $(DEPTH)/config/autoconf.mk

MOCHITEST_A11Y_FILES =\
		test_anchors.html \
		test_aria.html \
		test_general.html \
		test_general.xul \
		test_controls.html \
		test_keys_menu.xul \
		test_keys.html \
		test_link.html \
		test_media.html \
		test_select.html \
		test_tree.xul \
		test_treegrid.xul \
		$(NULL)

include $(topsrcdir)/config/rules.mk
