#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/scriptaculous/src
VPATH		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/scriptaculous/src
relativesrcdir	= dom/tests/mochitest/ajax/scriptaculous/src

include $(DEPTH)/config/autoconf.mk

DIRS	= \
	$(NULL)

MOCHITEST_FILES	= \
	builder.js \
	controls.js \
	dragdrop.js \
	effects.js \
	scriptaculous.js \
	slider.js \
	sound.js \
	unittest.js \
	$(NULL)

include $(topsrcdir)/config/rules.mk
