#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/intl/unicharutil/public
VPATH		= /home/txema/work/firefox-20.0+build1/intl/unicharutil/public

include $(DEPTH)/config/autoconf.mk

MODULE		= unicharutil

EXPORTS		= \
		nsICaseConversion.h \
		nsIUGenCategory.h \
		nsUnicharUtilCIID.h \
		nsUnicodeNormalizer.h \
		$(NULL)

include $(topsrcdir)/config/rules.mk

