# Any copyright is dedicated to the Public Domain.
# http://creativecommons.org/publicdomain/zero/1.0/

DEPTH     = ../../../../..
topsrcdir = /home/txema/work/firefox-20.0+build1
srcdir    = /home/txema/work/firefox-20.0+build1/browser/components/downloads/test/browser
VPATH     = /home/txema/work/firefox-20.0+build1/browser/components/downloads/test/browser

relativesrcdir = browser/components/downloads/test/browser

include $(DEPTH)/config/autoconf.mk

MOCHITEST_BROWSER_FILES = \
  browser_basic_functionality.js \
  browser_first_download_panel.js \
  head.js \
  $(NULL)

include $(topsrcdir)/config/rules.mk
