//
// Automatically generated by ipdlc.
// Edit at your own risk
//

#ifndef PIndexedDBObjectStoreParent_h
#define PIndexedDBObjectStoreParent_h

#include "mozilla/dom/indexedDB/PIndexedDBObjectStore.h"
namespace mozilla {
namespace dom {
class PBlobParent;
} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {
namespace indexedDB {
class PIndexedDBCursorParent;
} // namespace indexedDB
} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {
namespace indexedDB {
class PIndexedDBIndexParent;
} // namespace indexedDB
} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {
namespace indexedDB {
class PIndexedDBRequestParent;
} // namespace indexedDB
} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {
namespace indexedDB {
class PIndexedDBTransactionParent;
} // namespace indexedDB
} // namespace dom
} // namespace mozilla

#ifdef DEBUG
#include "prenv.h"
#endif // DEBUG
#include "base/id_map.h"
#include "mozilla/ipc/RPCChannel.h"


namespace mozilla {
namespace dom {
namespace indexedDB {
class PIndexedDBIndexParent;
} // namespace indexedDB
} // namespace dom
} // namespace mozilla


namespace mozilla {
namespace dom {
namespace indexedDB {
class PIndexedDBTransactionParent;
} // namespace indexedDB
} // namespace dom
} // namespace mozilla


namespace mozilla {
namespace dom {
namespace indexedDB {
class PIndexedDBCursorParent;
} // namespace indexedDB
} // namespace dom
} // namespace mozilla


namespace mozilla {
namespace dom {
namespace indexedDB {
class PIndexedDBRequestParent;
} // namespace indexedDB
} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {
namespace indexedDB {


class /*NS_ABSTRACT_CLASS*/ PIndexedDBObjectStoreParent :
    protected mozilla::ipc::RPCChannel::RPCListener,
    protected mozilla::ipc::IProtocolManager<mozilla::ipc::RPCChannel::RPCListener>
{
    friend class mozilla::dom::indexedDB::PIndexedDBIndexParent;

    friend class mozilla::dom::indexedDB::PIndexedDBTransactionParent;

    friend class mozilla::dom::indexedDB::PIndexedDBCursorParent;

    friend class mozilla::dom::indexedDB::PIndexedDBRequestParent;

protected:
    typedef mozilla::ipc::ActorHandle ActorHandle;
    typedef mozilla::dom::indexedDB::ipc::AddParams AddParams;
    typedef mozilla::dom::indexedDB::ipc::AddPutParams AddPutParams;
    typedef mozilla::dom::indexedDB::ipc::ClearParams ClearParams;
    typedef mozilla::dom::indexedDB::ipc::FIXME_Bug_521898_objectstore::CountParams CountParams;
    typedef mozilla::dom::indexedDB::ipc::CreateIndexParams CreateIndexParams;
    typedef mozilla::dom::indexedDB::ipc::DeleteParams DeleteParams;
    typedef mozilla::dom::indexedDB::IDBCursor::Direction Direction;
    typedef mozilla::ipc::FileDescriptor FileDescriptor;
    typedef mozilla::dom::indexedDB::ipc::FIXME_Bug_521898_objectstore::GetAllParams GetAllParams;
    typedef mozilla::dom::indexedDB::ipc::GetIndexParams GetIndexParams;
    typedef mozilla::dom::indexedDB::ipc::FIXME_Bug_521898_objectstore::GetParams GetParams;
    typedef mozilla::dom::indexedDB::ipc::IndexConstructorParams IndexConstructorParams;
    typedef mozilla::dom::indexedDB::IndexInfo IndexInfo;
    typedef mozilla::dom::indexedDB::IndexUpdateInfo IndexUpdateInfo;
    typedef mozilla::dom::indexedDB::Key Key;
    typedef mozilla::dom::indexedDB::ipc::FIXME_Bug_521898_objectstore::KeyRange KeyRange;
    typedef mozilla::dom::indexedDB::ipc::ObjectStoreCursorConstructorParams ObjectStoreCursorConstructorParams;
    typedef mozilla::dom::indexedDB::ipc::ObjectStoreRequestParams ObjectStoreRequestParams;
    typedef mozilla::dom::indexedDB::ipc::FIXME_Bug_521898_objectstore::OpenCursorParams OpenCursorParams;
    typedef mozilla::dom::indexedDB::ipc::FIXME_Bug_521898_objectstore::OptionalKeyRange OptionalKeyRange;
    typedef mozilla::dom::indexedDB::ipc::PutParams PutParams;
    typedef mozilla::dom::indexedDB::SerializedStructuredCloneReadInfo SerializedStructuredCloneReadInfo;
    typedef mozilla::dom::indexedDB::SerializedStructuredCloneWriteInfo SerializedStructuredCloneWriteInfo;
    typedef mozilla::ipc::Shmem Shmem;
    typedef mozilla::void_t void_t;
    typedef mozilla::dom::PBlobParent PBlobParent;
    typedef mozilla::dom::indexedDB::PIndexedDBCursorParent PIndexedDBCursorParent;
    typedef mozilla::dom::indexedDB::PIndexedDBIndexParent PIndexedDBIndexParent;
    typedef mozilla::dom::indexedDB::PIndexedDBRequestParent PIndexedDBRequestParent;
    typedef mozilla::dom::indexedDB::PIndexedDBTransactionParent PIndexedDBTransactionParent;
    typedef base::ProcessId ProcessId;
    typedef mozilla::ipc::ProtocolId ProtocolId;
    typedef mozilla::ipc::Transport Transport;
    typedef mozilla::ipc::TransportDescriptor TransportDescriptor;

    typedef PIndexedDBObjectStore::State State;

    virtual bool
    Recv__delete__();
    virtual bool
    RecvPIndexedDBIndexConstructor(
            PIndexedDBIndexParent* actor,
            const IndexConstructorParams& params);
    virtual bool
    RecvPIndexedDBRequestConstructor(
            PIndexedDBRequestParent* actor,
            const ObjectStoreRequestParams& params);
    virtual bool
    RecvDeleteIndex(const nsString& name) = 0;
    virtual PIndexedDBIndexParent*
    AllocPIndexedDBIndex(const IndexConstructorParams& params) = 0;
    virtual bool
    DeallocPIndexedDBIndex(PIndexedDBIndexParent* actor) = 0;
    virtual PIndexedDBRequestParent*
    AllocPIndexedDBRequest(const ObjectStoreRequestParams& params) = 0;
    virtual bool
    DeallocPIndexedDBRequest(PIndexedDBRequestParent* actor) = 0;
    virtual PIndexedDBCursorParent*
    AllocPIndexedDBCursor(const ObjectStoreCursorConstructorParams& params) = 0;
    virtual bool
    DeallocPIndexedDBCursor(PIndexedDBCursorParent* actor) = 0;

    virtual void
    ActorDestroy(ActorDestroyReason why);

public:
    typedef IPC::Message Message;
    typedef mozilla::ipc::RPCChannel Channel;
    typedef mozilla::ipc::RPCChannel::RPCListener ChannelListener;
    typedef base::ProcessHandle ProcessHandle;
    typedef mozilla::ipc::AsyncChannel AsyncChannel;
    typedef mozilla::ipc::SharedMemory SharedMemory;
    typedef mozilla::ipc::Trigger Trigger;

public:
    PIndexedDBObjectStoreParent();

    virtual ~PIndexedDBObjectStoreParent();

    PIndexedDBTransactionParent*
    Manager() const;

    void
    ManagedPIndexedDBCursorParent(InfallibleTArray<PIndexedDBCursorParent*>& aArr) const;
    const InfallibleTArray<PIndexedDBCursorParent*>&
    ManagedPIndexedDBCursorParent() const;

    void
    ManagedPIndexedDBIndexParent(InfallibleTArray<PIndexedDBIndexParent*>& aArr) const;
    const InfallibleTArray<PIndexedDBIndexParent*>&
    ManagedPIndexedDBIndexParent() const;

    void
    ManagedPIndexedDBRequestParent(InfallibleTArray<PIndexedDBRequestParent*>& aArr) const;
    const InfallibleTArray<PIndexedDBRequestParent*>&
    ManagedPIndexedDBRequestParent() const;

    PIndexedDBObjectStore::State
    state();

    PIndexedDBCursorParent*
    SendPIndexedDBCursorConstructor(const ObjectStoreCursorConstructorParams& params) NS_WARN_UNUSED_RESULT;

    PIndexedDBCursorParent*
    SendPIndexedDBCursorConstructor(
            PIndexedDBCursorParent* actor,
            const ObjectStoreCursorConstructorParams& params) NS_WARN_UNUSED_RESULT;

    virtual int32_t
    Register(ChannelListener* aRouted);
    virtual int32_t
    RegisterID(
            ChannelListener* aRouted,
            int32_t aId);
    virtual ChannelListener*
    Lookup(int32_t aId);
    virtual void
    Unregister(int32_t aId);
    virtual void
    RemoveManagee(
            int32_t aProtocolId,
            ChannelListener* aListener);
    virtual Shmem::SharedMemory*
    CreateSharedMemory(
            size_t aSize,
            Shmem::SharedMemory::SharedMemoryType aType,
            bool aUnsafe,
            Shmem::id_t* aId);
    virtual bool
    AdoptSharedMemory(
            Shmem::SharedMemory* segment,
            Shmem::id_t* aId);
    virtual Shmem::SharedMemory*
    LookupSharedMemory(Shmem::id_t aId);
    virtual bool
    IsTrackingSharedMemory(Shmem::SharedMemory* segment);
    virtual bool
    DestroySharedMemory(Shmem& shmem);
    virtual ProcessHandle
    OtherProcess() const;
    virtual AsyncChannel*
    GetIPCChannel();

    virtual Result
    OnMessageReceived(const Message& __msg);

    virtual Result
    OnMessageReceived(
            const Message& __msg,
            Message*& __reply);

    virtual Result
    OnCallReceived(
            const Message& __msg,
            Message*& __reply);

    void
    OnProcessingError(Result code);

    int32_t
    GetProtocolTypeId();

    bool
    OnReplyTimeout();

    void
    OnChannelClose();

    void
    OnChannelError();

    void
    OnChannelConnected(int32_t pid);

    // Methods for managing shmem
    bool
    AllocShmem(
            size_t aSize,
            Shmem::SharedMemory::SharedMemoryType aType,
            Shmem* aMem);

    bool
    AllocUnsafeShmem(
            size_t aSize,
            Shmem::SharedMemory::SharedMemoryType aType,
            Shmem* aMem);

    bool
    AdoptShmem(
            Shmem& aMem,
            Shmem* aOutMem);

    bool
    DeallocShmem(Shmem& aMem);

private:
    virtual void
    FatalError(const char* const msg) const;

    void
    DestroySubtree(ActorDestroyReason why);

    void
    DeallocSubtree();

    template<typename T>
    void
    Write(
            const T& __v,
            Message* __msg)
    {
        IPC::WriteParam(__msg, __v);
    }

    template<typename T>
    bool
    Read(
            T* __v,
            const Message* __msg,
            void** __iter)
    {
        return IPC::ReadParam(__msg, __iter, __v);
    }

    void
    Write(
            const ObjectStoreCursorConstructorParams& __v,
            Message* __msg);

    bool
    Read(
            ObjectStoreCursorConstructorParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const OpenCursorParams& __v,
            Message* __msg);

    bool
    Read(
            OpenCursorParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const IndexConstructorParams& __v,
            Message* __msg);

    bool
    Read(
            IndexConstructorParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const AddParams& __v,
            Message* __msg);

    bool
    Read(
            AddParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const PutParams& __v,
            Message* __msg);

    bool
    Read(
            PutParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const KeyRange& __v,
            Message* __msg);

    bool
    Read(
            KeyRange* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            PBlobParent* __v,
            Message* __msg,
            bool __nullable);

    bool
    Read(
            PBlobParent** __v,
            const Message* __msg,
            void** __iter,
            bool __nullable) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const GetAllParams& __v,
            Message* __msg);

    bool
    Read(
            GetAllParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            PIndexedDBCursorParent* __v,
            Message* __msg,
            bool __nullable);

    bool
    Read(
            PIndexedDBCursorParent** __v,
            const Message* __msg,
            void** __iter,
            bool __nullable) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const DeleteParams& __v,
            Message* __msg);

    bool
    Read(
            DeleteParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const OptionalKeyRange& __v,
            Message* __msg);

    bool
    Read(
            OptionalKeyRange* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const GetIndexParams& __v,
            Message* __msg);

    bool
    Read(
            GetIndexParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const InfallibleTArray<PBlobParent*>& __v,
            Message* __msg);

    bool
    Read(
            InfallibleTArray<PBlobParent*>* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const ObjectStoreRequestParams& __v,
            Message* __msg);

    bool
    Read(
            ObjectStoreRequestParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            PIndexedDBRequestParent* __v,
            Message* __msg,
            bool __nullable);

    bool
    Read(
            PIndexedDBRequestParent** __v,
            const Message* __msg,
            void** __iter,
            bool __nullable) NS_WARN_UNUSED_RESULT;

    void
    Write(
            PIndexedDBIndexParent* __v,
            Message* __msg,
            bool __nullable);

    bool
    Read(
            PIndexedDBIndexParent** __v,
            const Message* __msg,
            void** __iter,
            bool __nullable) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const CreateIndexParams& __v,
            Message* __msg);

    bool
    Read(
            CreateIndexParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const AddPutParams& __v,
            Message* __msg);

    bool
    Read(
            AddPutParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const CountParams& __v,
            Message* __msg);

    bool
    Read(
            CountParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const GetParams& __v,
            Message* __msg);

    bool
    Read(
            GetParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    void
    Write(
            PIndexedDBObjectStoreParent* __v,
            Message* __msg,
            bool __nullable);

    bool
    Read(
            PIndexedDBObjectStoreParent** __v,
            const Message* __msg,
            void** __iter,
            bool __nullable) NS_WARN_UNUSED_RESULT;

    void
    Write(
            const ClearParams& __v,
            Message* __msg);

    bool
    Read(
            ClearParams* __v,
            const Message* __msg,
            void** __iter) NS_WARN_UNUSED_RESULT;

    Channel* mChannel;
    mozilla::ipc::IProtocolManager<mozilla::ipc::RPCChannel::RPCListener>* mManager;
    int32_t mId;
    State mState;
    // Sorted by pointer value
    InfallibleTArray<PIndexedDBCursorParent*> mManagedPIndexedDBCursorParent;
    // Sorted by pointer value
    InfallibleTArray<PIndexedDBIndexParent*> mManagedPIndexedDBIndexParent;
    // Sorted by pointer value
    InfallibleTArray<PIndexedDBRequestParent*> mManagedPIndexedDBRequestParent;
};


} // namespace indexedDB
} // namespace dom
} // namespace mozilla

#if 0

//-----------------------------------------------------------------------------
// Skeleton implementation of abstract actor class

// Header file contents
namespace mozilla {
namespace dom {
namespace indexedDB {
class IndexedDBObjectStoreParent :
    public PIndexedDBObjectStoreParent
{
    virtual bool
    RecvDeleteIndex(const nsString& name);

    virtual PIndexedDBIndexParent*
    AllocPIndexedDBIndex(const IndexConstructorParams& params);

    virtual bool
    DeallocPIndexedDBIndex(PIndexedDBIndexParent* actor);

    virtual PIndexedDBRequestParent*
    AllocPIndexedDBRequest(const ObjectStoreRequestParams& params);

    virtual bool
    DeallocPIndexedDBRequest(PIndexedDBRequestParent* actor);

    virtual PIndexedDBCursorParent*
    AllocPIndexedDBCursor(const ObjectStoreCursorConstructorParams& params);

    virtual bool
    DeallocPIndexedDBCursor(PIndexedDBCursorParent* actor);

    IndexedDBObjectStoreParent();
    virtual ~IndexedDBObjectStoreParent();
};
} // namespace indexedDB
} // namespace dom
} // namespace mozilla


// C++ file contents
namespace mozilla {
namespace dom {
namespace indexedDB {
bool
IndexedDBObjectStoreParent::RecvDeleteIndex(const nsString& name)
{
    return false;
}

PIndexedDBIndexParent*
IndexedDBObjectStoreParent::AllocPIndexedDBIndex(const IndexConstructorParams& params)
{
    return 0;
}

bool
IndexedDBObjectStoreParent::DeallocPIndexedDBIndex(PIndexedDBIndexParent* actor)
{
    return false;
}

PIndexedDBRequestParent*
IndexedDBObjectStoreParent::AllocPIndexedDBRequest(const ObjectStoreRequestParams& params)
{
    return 0;
}

bool
IndexedDBObjectStoreParent::DeallocPIndexedDBRequest(PIndexedDBRequestParent* actor)
{
    return false;
}

PIndexedDBCursorParent*
IndexedDBObjectStoreParent::AllocPIndexedDBCursor(const ObjectStoreCursorConstructorParams& params)
{
    return 0;
}

bool
IndexedDBObjectStoreParent::DeallocPIndexedDBCursor(PIndexedDBCursorParent* actor)
{
    return false;
}

IndexedDBObjectStoreParent::IndexedDBObjectStoreParent()
{
    MOZ_COUNT_CTOR(IndexedDBObjectStoreParent);
}

IndexedDBObjectStoreParent::~IndexedDBObjectStoreParent()
{
    MOZ_COUNT_DTOR(IndexedDBObjectStoreParent);
}

} // namespace indexedDB
} // namespace dom
} // namespace mozilla
#endif // if 0

#endif // ifndef PIndexedDBObjectStoreParent_h
