#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/layout/inspector/tests
VPATH		= /home/txema/work/firefox-20.0+build1/layout/inspector/tests
relativesrcdir	= layout/inspector/tests

include $(DEPTH)/config/autoconf.mk

MOCHITEST_FILES =\
		test_bug462787.html \
		test_bug462789.html \
		test_bug522601.xhtml \
		test_bug536379.html \
		test_bug536379-2.html \
		test_bug557726.html \
		test_bug609549.xhtml \
		test_bug806192.html \
		test_isinheritableproperty.html \
		$(NULL)

include $(topsrcdir)/config/rules.mk
