# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH            = ../../..
topsrcdir        = /home/txema/work/firefox-20.0+build1
srcdir           = /home/txema/work/firefox-20.0+build1/dom/alarm/test
VPATH            = /home/txema/work/firefox-20.0+build1/dom/alarm/test

relativesrcdir   = dom/alarm/test

include $(DEPTH)/config/autoconf.mk

DIRS = \
  $(NULL)

MOCHITEST_FILES = \
  test_alarm_permitted_app.html \
  test_alarm_non_permitted_app.html \
  $(NULL)

include $(topsrcdir)/config/rules.mk
