#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../../../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/jquery/test/data/offset
VPATH		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/jquery/test/data/offset
relativesrcdir	= dom/tests/mochitest/ajax/jquery/test/data/offset

include $(DEPTH)/config/autoconf.mk

DIRS	= \
	$(NULL)

MOCHITEST_FILES	= \
	absolute.html \
	fixed.html \
	relative.html \
	scroll.html \
	static.html \
	table.html \
	$(NULL)

include $(topsrcdir)/config/rules.mk
