# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH          = ../../../..
topsrcdir      = /home/txema/work/firefox-20.0+build1
srcdir         = /home/txema/work/firefox-20.0+build1/toolkit/identity/tests/mochitest
VPATH          = /home/txema/work/firefox-20.0+build1/toolkit/identity/tests/mochitest
relativesrcdir = toolkit/identity/tests/mochitest

include $(DEPTH)/config/autoconf.mk

# XXX bug 805602 update and restore mochitests

include $(topsrcdir)/config/rules.mk
