#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/caps
VPATH		= /home/txema/work/firefox-20.0+build1/caps

include $(DEPTH)/config/autoconf.mk

MODULE		= caps
DIRS		= idl include src

TEST_DIRS += tests/mochitest

include $(topsrcdir)/config/rules.mk

