# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH          = ../../..
topsrcdir      = /home/txema/work/firefox-20.0+build1
srcdir         = /home/txema/work/firefox-20.0+build1/services/metrics/tests
VPATH          = /home/txema/work/firefox-20.0+build1/services/metrics/tests
relativesrcdir = services/metrics/tests

include $(DEPTH)/config/autoconf.mk

XPCSHELL_TESTS = xpcshell

include $(topsrcdir)/config/rules.mk
