#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/intl/locale/public
VPATH		= /home/txema/work/firefox-20.0+build1/intl/locale/public

include $(DEPTH)/config/autoconf.mk

MODULE		= locale

EXPORTS		= \
		nsCollationCID.h \
		nsDateTimeFormatCID.h \
		nsIDateTimeFormat.h \
		nsILanguageAtomService.h \
		nsPosixLocale.h \
		nsIOS2Locale.h \
		nsWin32Locale.h \
		nsCharsetAlias.h \
		nsIPlatformCharset.h \
		nsLocaleCID.h \
		$(NULL)

include $(topsrcdir)/config/rules.mk

