# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH          = ../../../..
topsrcdir      = /home/txema/work/firefox-20.0+build1
srcdir         = /home/txema/work/firefox-20.0+build1/browser/devtools/profiler/test
VPATH          = /home/txema/work/firefox-20.0+build1/browser/devtools/profiler/test
relativesrcdir = browser/devtools/profiler/test

include $(DEPTH)/config/autoconf.mk

# Profiler tests disabled for Beta.
# MOCHITEST_BROWSER_FILES = \
#		browser_profiler_run.js \
#		browser_profiler_controller.js \
#		browser_profiler_profiles.js \
#		head.js \

include $(topsrcdir)/config/rules.mk
