#include "AudioBufferBinding.h"
#include "AudioBufferSourceNodeBinding.h"
#include "AudioContextBinding.h"
#include "AudioDestinationNodeBinding.h"
#include "AudioListenerBinding.h"
#include "AudioNodeBinding.h"
#include "AudioParamBinding.h"
#include "AudioSourceNodeBinding.h"
#include "BiquadFilterNodeBinding.h"
#include "CDATASectionBinding.h"
#include "CSS2PropertiesBinding.h"
#include "CSSBinding.h"
#include "CSSPrimitiveValueBinding.h"
#include "CSSStyleDeclarationBinding.h"
#include "CSSValueBinding.h"
#include "CSSValueListBinding.h"
#include "CanvasRenderingContext2DBinding.h"
#include "CaretPositionBinding.h"
#include "CharacterDataBinding.h"
#include "ClientRectListBinding.h"
#include "CommentBinding.h"
#include "DOMImplementationBinding.h"
#include "DOMParserBinding.h"
#include "DOMSettableTokenListBinding.h"
#include "DOMStringMapBinding.h"
#include "DOMTokenListBinding.h"
#include "DelayNodeBinding.h"
#include "DocumentBinding.h"
#include "DocumentFragmentBinding.h"
#include "DocumentTypeBinding.h"
#include "DynamicsCompressorNodeBinding.h"
#include "ElementBinding.h"
#include "EventSourceBinding.h"
#include "EventTargetBinding.h"
#include "FileHandleBinding.h"
#include "FileListBinding.h"
#include "FormDataBinding.h"
#include "GainNodeBinding.h"
#include "HTMLAnchorElementBinding.h"
#include "HTMLBodyElementBinding.h"
#include "HTMLCollectionBinding.h"
#include "HTMLDListElementBinding.h"
#include "HTMLDataListElementBinding.h"
#include "HTMLDivElementBinding.h"
#include "HTMLElementBinding.h"
#include "HTMLFontElementBinding.h"
#include "HTMLFrameSetElementBinding.h"
#include "HTMLHeadingElementBinding.h"
#include "HTMLImageElementBinding.h"
#include "HTMLLIElementBinding.h"
#include "HTMLLabelElementBinding.h"
#include "HTMLOListElementBinding.h"
#include "HTMLOptionsCollectionBinding.h"
#include "HTMLParagraphElementBinding.h"
#include "HTMLPreElementBinding.h"
#include "HTMLPropertiesCollectionBinding.h"
#include "HTMLScriptElementBinding.h"
#include "HTMLSpanElementBinding.h"
#include "HTMLTableCaptionElementBinding.h"
#include "HTMLTableCellElementBinding.h"
#include "HTMLTableColElementBinding.h"
#include "HTMLTableElementBinding.h"
#include "HTMLTableRowElementBinding.h"
#include "HTMLTableSectionElementBinding.h"
#include "HTMLTitleElementBinding.h"
#include "HTMLUListElementBinding.h"
#include "ImageDataBinding.h"
#include "MutationObserverBinding.h"
#include "NodeBinding.h"
#include "NodeFilterBinding.h"
#include "NodeListBinding.h"
#include "PaintRequestBinding.h"
#include "PaintRequestListBinding.h"
#include "PannerNodeBinding.h"
#include "PerformanceBinding.h"
#include "PerformanceNavigationBinding.h"
#include "PerformanceTimingBinding.h"
#include "ProcessingInstructionBinding.h"
#include "RGBColorBinding.h"
#include "RectBinding.h"
#include "SVGAltGlyphElementBinding.h"
#include "SVGAngleBinding.h"
#include "SVGAnimateElementBinding.h"
#include "SVGAnimateMotionElementBinding.h"
#include "SVGAnimateTransformElementBinding.h"
#include "SVGAnimatedAngleBinding.h"
#include "SVGAnimatedBooleanBinding.h"
#include "SVGAnimatedLengthListBinding.h"
#include "SVGAnimatedNumberListBinding.h"
#include "SVGAnimatedPreserveAspectRatioBinding.h"
#include "SVGAnimatedTransformListBinding.h"
#include "SVGAnimationElementBinding.h"
#include "SVGCircleElementBinding.h"
#include "SVGDefsElementBinding.h"
#include "SVGDescElementBinding.h"
#include "SVGElementBinding.h"
#include "SVGEllipseElementBinding.h"
#include "SVGForeignObjectElementBinding.h"
#include "SVGGElementBinding.h"
#include "SVGGraphicsElementBinding.h"
#include "SVGImageElementBinding.h"
#include "SVGLengthListBinding.h"
#include "SVGLineElementBinding.h"
#include "SVGLocatableElementBinding.h"
#include "SVGMPathElementBinding.h"
#include "SVGMatrixBinding.h"
#include "SVGMetadataElementBinding.h"
#include "SVGNumberListBinding.h"
#include "SVGPathSegBinding.h"
#include "SVGPathSegListBinding.h"
#include "SVGPointBinding.h"
#include "SVGPointListBinding.h"
#include "SVGPolygonElementBinding.h"
#include "SVGPolylineElementBinding.h"
#include "SVGPreserveAspectRatioBinding.h"
#include "SVGRectElementBinding.h"
#include "SVGScriptElementBinding.h"
#include "SVGSetElementBinding.h"
#include "SVGStopElementBinding.h"
#include "SVGStyleElementBinding.h"
#include "SVGSwitchElementBinding.h"
#include "SVGTSpanElementBinding.h"
#include "SVGTextContentElementBinding.h"
#include "SVGTextElementBinding.h"
#include "SVGTextPathElementBinding.h"
#include "SVGTextPositioningElementBinding.h"
#include "SVGTitleElementBinding.h"
#include "SVGTransformBinding.h"
#include "SVGTransformListBinding.h"
#include "SVGTransformableElementBinding.h"
#include "ScreenBinding.h"
#include "TextBinding.h"
#include "TextDecoderBinding.h"
#include "TextEncoderBinding.h"
#include "URLBinding.h"
#include "UndoManagerBinding.h"
#include "WebGLRenderingContextBinding.h"
#include "WebSocketBinding.h"
#include "XMLHttpRequestBinding.h"
#include "XMLHttpRequestUploadBinding.h"
#include "XMLSerializerBinding.h"
#include "XPathEvaluatorBinding.h"
#include "nsScriptNameSpaceManager.h"

namespace mozilla {
namespace dom {
void
Register(nsScriptNameSpaceManager* aNameSpaceManager)
{

#define REGISTER_PROTO(_dom_class, _pref_check) \
  aNameSpaceManager->RegisterDefineDOMInterface(NS_LITERAL_STRING(#_dom_class), _dom_class##Binding::DefineDOMInterface, _pref_check);

REGISTER_PROTO(AudioBuffer, AudioBufferBinding::PrefEnabled);
REGISTER_PROTO(AudioBufferSourceNode, AudioBufferSourceNodeBinding::PrefEnabled);
REGISTER_PROTO(AudioDestinationNode, AudioDestinationNodeBinding::PrefEnabled);
REGISTER_PROTO(AudioListener, AudioListenerBinding::PrefEnabled);
REGISTER_PROTO(AudioNode, AudioNodeBinding::PrefEnabled);
REGISTER_PROTO(AudioParam, AudioParamBinding::PrefEnabled);
REGISTER_PROTO(AudioSourceNode, AudioSourceNodeBinding::PrefEnabled);
REGISTER_PROTO(BiquadFilterNode, BiquadFilterNodeBinding::PrefEnabled);
REGISTER_PROTO(CDATASection, nullptr);
REGISTER_PROTO(CSS, CSSBinding::PrefEnabled);
REGISTER_PROTO(CSS2Properties, nullptr);
REGISTER_PROTO(CSSPrimitiveValue, nullptr);
REGISTER_PROTO(CSSStyleDeclaration, nullptr);
REGISTER_PROTO(CSSValue, nullptr);
REGISTER_PROTO(CSSValueList, nullptr);
REGISTER_PROTO(CanvasRenderingContext2D, nullptr);
REGISTER_PROTO(CaretPosition, nullptr);
REGISTER_PROTO(CharacterData, nullptr);
REGISTER_PROTO(ClientRectList, nullptr);
REGISTER_PROTO(Comment, nullptr);
REGISTER_PROTO(DOMImplementation, nullptr);
REGISTER_PROTO(DOMParser, nullptr);
REGISTER_PROTO(DOMSettableTokenList, nullptr);
REGISTER_PROTO(DOMStringMap, nullptr);
REGISTER_PROTO(DOMTokenList, nullptr);
REGISTER_PROTO(DelayNode, DelayNodeBinding::PrefEnabled);
REGISTER_PROTO(Document, nullptr);
REGISTER_PROTO(DocumentFragment, nullptr);
REGISTER_PROTO(DocumentType, nullptr);
REGISTER_PROTO(DynamicsCompressorNode, DynamicsCompressorNodeBinding::PrefEnabled);
REGISTER_PROTO(Element, nullptr);
REGISTER_PROTO(EventSource, EventSourceBinding::PrefEnabled);
REGISTER_PROTO(EventTarget, nullptr);
REGISTER_PROTO(FileHandle, nullptr);
REGISTER_PROTO(FileList, nullptr);
REGISTER_PROTO(FormData, nullptr);
REGISTER_PROTO(GainNode, GainNodeBinding::PrefEnabled);
REGISTER_PROTO(HTMLAnchorElement, nullptr);
REGISTER_PROTO(HTMLBodyElement, nullptr);
REGISTER_PROTO(HTMLCollection, nullptr);
REGISTER_PROTO(HTMLDListElement, nullptr);
REGISTER_PROTO(HTMLDataListElement, nullptr);
REGISTER_PROTO(HTMLDivElement, nullptr);
REGISTER_PROTO(HTMLElement, HTMLElementBinding::PrefEnabled);
REGISTER_PROTO(HTMLFontElement, nullptr);
REGISTER_PROTO(HTMLFrameSetElement, nullptr);
REGISTER_PROTO(HTMLHeadingElement, nullptr);
REGISTER_PROTO(HTMLImageElement, nullptr);
REGISTER_PROTO(HTMLLIElement, nullptr);
REGISTER_PROTO(HTMLLabelElement, nullptr);
REGISTER_PROTO(HTMLOListElement, nullptr);
REGISTER_PROTO(HTMLOptionsCollection, nullptr);
REGISTER_PROTO(HTMLParagraphElement, nullptr);
REGISTER_PROTO(HTMLPreElement, nullptr);
REGISTER_PROTO(HTMLPropertiesCollection, nullptr);
REGISTER_PROTO(HTMLScriptElement, nullptr);
REGISTER_PROTO(HTMLSpanElement, nullptr);
REGISTER_PROTO(HTMLTableCaptionElement, nullptr);
REGISTER_PROTO(HTMLTableCellElement, nullptr);
REGISTER_PROTO(HTMLTableColElement, nullptr);
REGISTER_PROTO(HTMLTableElement, nullptr);
REGISTER_PROTO(HTMLTableRowElement, nullptr);
REGISTER_PROTO(HTMLTableSectionElement, nullptr);
REGISTER_PROTO(HTMLTitleElement, nullptr);
REGISTER_PROTO(HTMLUListElement, nullptr);
REGISTER_PROTO(HTMLUnknownElement, nullptr);
REGISTER_PROTO(ImageData, nullptr);
REGISTER_PROTO(MutationObserver, nullptr);
REGISTER_PROTO(MutationRecord, nullptr);
REGISTER_PROTO(Node, nullptr);
REGISTER_PROTO(NodeFilter, nullptr);
REGISTER_PROTO(NodeList, nullptr);
REGISTER_PROTO(PaintRequest, nullptr);
REGISTER_PROTO(PaintRequestList, nullptr);
REGISTER_PROTO(PannerNode, PannerNodeBinding::PrefEnabled);
REGISTER_PROTO(Performance, nullptr);
REGISTER_PROTO(PerformanceNavigation, nullptr);
REGISTER_PROTO(PerformanceTiming, nullptr);
REGISTER_PROTO(ProcessingInstruction, nullptr);
REGISTER_PROTO(PropertyNodeList, nullptr);
REGISTER_PROTO(RGBColor, nullptr);
REGISTER_PROTO(Rect, nullptr);
REGISTER_PROTO(SVGAltGlyphElement, nullptr);
REGISTER_PROTO(SVGAngle, nullptr);
REGISTER_PROTO(SVGAnimateElement, nullptr);
REGISTER_PROTO(SVGAnimateMotionElement, nullptr);
REGISTER_PROTO(SVGAnimateTransformElement, nullptr);
REGISTER_PROTO(SVGAnimatedAngle, nullptr);
REGISTER_PROTO(SVGAnimatedBoolean, nullptr);
REGISTER_PROTO(SVGAnimatedLengthList, nullptr);
REGISTER_PROTO(SVGAnimatedNumberList, nullptr);
REGISTER_PROTO(SVGAnimatedPreserveAspectRatio, nullptr);
REGISTER_PROTO(SVGAnimatedTransformList, nullptr);
REGISTER_PROTO(SVGAnimationElement, nullptr);
REGISTER_PROTO(SVGCircleElement, nullptr);
REGISTER_PROTO(SVGDefsElement, nullptr);
REGISTER_PROTO(SVGDescElement, nullptr);
REGISTER_PROTO(SVGElement, SVGElementBinding::PrefEnabled);
REGISTER_PROTO(SVGEllipseElement, nullptr);
REGISTER_PROTO(SVGForeignObjectElement, nullptr);
REGISTER_PROTO(SVGGElement, nullptr);
REGISTER_PROTO(SVGGraphicsElement, nullptr);
REGISTER_PROTO(SVGImageElement, nullptr);
REGISTER_PROTO(SVGLengthList, nullptr);
REGISTER_PROTO(SVGLineElement, nullptr);
REGISTER_PROTO(SVGLocatableElement, nullptr);
REGISTER_PROTO(SVGMPathElement, nullptr);
REGISTER_PROTO(SVGMatrix, nullptr);
REGISTER_PROTO(SVGMetadataElement, nullptr);
REGISTER_PROTO(SVGNumberList, nullptr);
REGISTER_PROTO(SVGPathSeg, nullptr);
REGISTER_PROTO(SVGPathSegArcAbs, nullptr);
REGISTER_PROTO(SVGPathSegArcRel, nullptr);
REGISTER_PROTO(SVGPathSegClosePath, nullptr);
REGISTER_PROTO(SVGPathSegCurvetoCubicAbs, nullptr);
REGISTER_PROTO(SVGPathSegCurvetoCubicRel, nullptr);
REGISTER_PROTO(SVGPathSegCurvetoCubicSmoothAbs, nullptr);
REGISTER_PROTO(SVGPathSegCurvetoCubicSmoothRel, nullptr);
REGISTER_PROTO(SVGPathSegCurvetoQuadraticAbs, nullptr);
REGISTER_PROTO(SVGPathSegCurvetoQuadraticRel, nullptr);
REGISTER_PROTO(SVGPathSegCurvetoQuadraticSmoothAbs, nullptr);
REGISTER_PROTO(SVGPathSegCurvetoQuadraticSmoothRel, nullptr);
REGISTER_PROTO(SVGPathSegLinetoAbs, nullptr);
REGISTER_PROTO(SVGPathSegLinetoHorizontalAbs, nullptr);
REGISTER_PROTO(SVGPathSegLinetoHorizontalRel, nullptr);
REGISTER_PROTO(SVGPathSegLinetoRel, nullptr);
REGISTER_PROTO(SVGPathSegLinetoVerticalAbs, nullptr);
REGISTER_PROTO(SVGPathSegLinetoVerticalRel, nullptr);
REGISTER_PROTO(SVGPathSegList, nullptr);
REGISTER_PROTO(SVGPathSegMovetoAbs, nullptr);
REGISTER_PROTO(SVGPathSegMovetoRel, nullptr);
REGISTER_PROTO(SVGPoint, nullptr);
REGISTER_PROTO(SVGPointList, nullptr);
REGISTER_PROTO(SVGPolygonElement, nullptr);
REGISTER_PROTO(SVGPolylineElement, nullptr);
REGISTER_PROTO(SVGPreserveAspectRatio, nullptr);
REGISTER_PROTO(SVGRectElement, nullptr);
REGISTER_PROTO(SVGScriptElement, nullptr);
REGISTER_PROTO(SVGSetElement, nullptr);
REGISTER_PROTO(SVGStopElement, nullptr);
REGISTER_PROTO(SVGStyleElement, nullptr);
REGISTER_PROTO(SVGSwitchElement, nullptr);
REGISTER_PROTO(SVGTSpanElement, nullptr);
REGISTER_PROTO(SVGTextContentElement, nullptr);
REGISTER_PROTO(SVGTextElement, nullptr);
REGISTER_PROTO(SVGTextPathElement, nullptr);
REGISTER_PROTO(SVGTextPositioningElement, nullptr);
REGISTER_PROTO(SVGTitleElement, nullptr);
REGISTER_PROTO(SVGTransform, nullptr);
REGISTER_PROTO(SVGTransformList, nullptr);
REGISTER_PROTO(SVGTransformableElement, nullptr);
REGISTER_PROTO(Screen, nullptr);
REGISTER_PROTO(Text, nullptr);
REGISTER_PROTO(TextDecoder, nullptr);
REGISTER_PROTO(TextEncoder, nullptr);
REGISTER_PROTO(URL, nullptr);
REGISTER_PROTO(UndoManager, UndoManagerBinding::PrefEnabled);
REGISTER_PROTO(WebGLActiveInfo, nullptr);
REGISTER_PROTO(WebGLBuffer, nullptr);
REGISTER_PROTO(WebGLFramebuffer, nullptr);
REGISTER_PROTO(WebGLProgram, nullptr);
REGISTER_PROTO(WebGLRenderbuffer, nullptr);
REGISTER_PROTO(WebGLRenderingContext, nullptr);
REGISTER_PROTO(WebGLShader, nullptr);
REGISTER_PROTO(WebGLShaderPrecisionFormat, nullptr);
REGISTER_PROTO(WebGLTexture, nullptr);
REGISTER_PROTO(WebGLUniformLocation, nullptr);
REGISTER_PROTO(WebSocket, WebSocketBinding::PrefEnabled);
REGISTER_PROTO(XMLHttpRequest, nullptr);
REGISTER_PROTO(XMLHttpRequestUpload, nullptr);
REGISTER_PROTO(XMLSerializer, nullptr);
REGISTER_PROTO(XPathEvaluator, nullptr);
REGISTER_PROTO(mozAudioContext, mozAudioContextBinding::PrefEnabled);

#undef REGISTER_PROTO
}

} // namespace dom
} // namespace mozilla

