#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH          = ../../../..
topsrcdir      = /home/txema/work/firefox-20.0+build1
srcdir         = /home/txema/work/firefox-20.0+build1/dom/src/json/test
VPATH          = /home/txema/work/firefox-20.0+build1/dom/src/json/test
relativesrcdir  = dom/src/json/test

include $(DEPTH)/config/autoconf.mk

MODULE         = json_test

XPCSHELL_TESTS = unit

 MOCHITEST_FILES =	test_json.html \
		$(NULL)

include $(topsrcdir)/config/rules.mk

