# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/browser/themes/gnomestripe
VPATH		= /home/txema/work/firefox-20.0+build1/browser/themes/gnomestripe

include $(DEPTH)/config/autoconf.mk

DIRS = communicator

ICON_FILES := icon.png
ICON_DEST = $(FINAL_TARGET)/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}
INSTALL_TARGETS += ICON

include $(topsrcdir)/config/rules.mk
