DEPTH           = ../../..
topsrcdir       = /home/txema/work/firefox-20.0+build1
srcdir          = /home/txema/work/firefox-20.0+build1/dom/system/tests
VPATH           = /home/txema/work/firefox-20.0+build1/dom/system/tests
relativesrcdir  = dom/system/tests

MODULE          = test_domsystem
MOCHITEST_CHROME_FILES = \
	test_constants.xul \
	worker_constants.js \
        $(NULL)

include $(topsrcdir)/config/rules.mk
