#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/accessible/tests/mochitest/treeupdate
VPATH		= /home/txema/work/firefox-20.0+build1/accessible/tests/mochitest/treeupdate
relativesrcdir  = accessible/treeupdate

include $(DEPTH)/config/autoconf.mk

MOCHITEST_A11Y_FILES =\
		test_ariadialog.html \
		test_canvas.html \
		test_colorpicker.xul \
		test_cssoverflow.html \
		test_contextmenu.xul \
		test_deck.xul \
		test_doc.html \
		test_gencontent.html \
		test_hidden.html \
		test_imagemap.html \
		test_list_editabledoc.html \
		test_list.html \
		test_listbox.xul \
		test_menu.xul \
		test_menubutton.xul \
		test_recreation.html \
		test_select.html \
		test_textleaf.html \
		test_visibility.html \
		test_whitespace.html \
		$(NULL)

include $(topsrcdir)/config/rules.mk
