#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/accessible/tests/mochitest/text
VPATH		= /home/txema/work/firefox-20.0+build1/accessible/tests/mochitest/text
relativesrcdir  = accessible/text

include $(DEPTH)/config/autoconf.mk

MOCHITEST_A11Y_FILES = \
		doc.html \
		test_doc.html \
		test_hypertext.html \
		test_passwords.html \
		test_selection.html \
		test_singleline.html \
		test_whitespaces.html \
		test_words.html \
		$(NULL)

include $(topsrcdir)/config/rules.mk
