#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/offline/namespace1
VPATH		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/offline/namespace1
relativesrcdir	= dom/tests/mochitest/ajax/offline/namespace1

include $(DEPTH)/config/autoconf.mk

DIRS = sub sub2

MOCHITEST_FILES	= \
        opp.html \
        script.js \
        redirectToDifferentOrigin.sjs \
        $(NULL)

include $(topsrcdir)/config/rules.mk
