//
// Automatically generated by ipdlc.
// Edit at your own risk
//


#include "mozilla/layers/PCompositorParent.h"
#ifdef MOZ_CRASHREPORTER
#  include "nsXULAppAPI.h"
#endif 

#include "mozilla/layers/PGrallocBufferParent.h"
#include "mozilla/layers/PLayersParent.h"

typedef IPC::Message Message;
typedef mozilla::ipc::RPCChannel Channel;
typedef mozilla::ipc::RPCChannel::RPCListener ChannelListener;
typedef base::ProcessHandle ProcessHandle;
typedef mozilla::ipc::AsyncChannel AsyncChannel;
typedef mozilla::ipc::SharedMemory SharedMemory;
typedef mozilla::ipc::Trigger Trigger;
typedef mozilla::ipc::ActorHandle ActorHandle;
typedef mozilla::ipc::FileDescriptor FileDescriptor;
typedef mozilla::layers::FrameMetrics FrameMetrics;
typedef mozilla::GraphicsFilterType GraphicsFilterType;
typedef mozilla::layers::LayersBackend LayersBackend;
typedef mozilla::layers::MagicGrallocBufferHandle MagicGrallocBufferHandle;
typedef mozilla::layers::MaybeMagicGrallocBufferHandle MaybeMagicGrallocBufferHandle;
typedef mozilla::layers::RGBImage RGBImage;
typedef mozilla::layers::SharedImage SharedImage;
typedef mozilla::layers::SharedImageID SharedImageID;
typedef mozilla::layers::SharedTextureDescriptor SharedTextureDescriptor;
typedef mozilla::gl::SharedTextureHandle SharedTextureHandle;
typedef mozilla::gl::GLContext::SharedTextureShareType SharedTextureShareType;
typedef mozilla::ipc::Shmem Shmem;
typedef mozilla::layers::SurfaceDescriptor SurfaceDescriptor;
typedef mozilla::layers::SurfaceDescriptorD3D10 SurfaceDescriptorD3D10;
typedef mozilla::layers::SurfaceDescriptorGralloc SurfaceDescriptorGralloc;
typedef mozilla::layers::SurfaceDescriptorX11 SurfaceDescriptorX11;
typedef mozilla::WindowsHandle WindowsHandle;
typedef mozilla::layers::YCbCrImage YCbCrImage;
typedef mozilla::layers::YUVImage YUVImage;
typedef mozilla::gfxContentType gfxContentType;
typedef mozilla::null_t null_t;
using mozilla::layers::PGrallocBufferParent;
using mozilla::layers::PLayersParent;

namespace mozilla {
namespace layers {


bool
PCompositorParent::RecvPLayersConstructor(
        PLayersParent* actor,
        const LayersBackend& backendHint,
        const uint64_t& id,
        LayersBackend* backend,
        int32_t* maxTextureSize)
{
    return true;
}

bool
PCompositorParent::RecvPGrallocBufferConstructor(
        PGrallocBufferParent* actor,
        const gfxIntSize& size,
        const uint32_t& format,
        const uint32_t& usage,
        MaybeMagicGrallocBufferHandle* handle)
{
    return true;
}

void
PCompositorParent::ActorDestroy(ActorDestroyReason why)
{
}

void
PCompositorParent::ProcessingError(Result code)
{
}

bool
PCompositorParent::ShouldContinueFromReplyTimeout()
{
    return true;
}

void
PCompositorParent::EnteredCxxStack()
{
}

void
PCompositorParent::ExitedCxxStack()
{
}

void
PCompositorParent::EnteredCall()
{
}

void
PCompositorParent::ExitedCall()
{
}

PCompositorParent::PCompositorParent() :
    mChannel(ALLOW_THIS_IN_INITIALIZER_LIST(this)),
    mLastRouteId(1),
    mLastShmemId(1),
    mState(PCompositor::__Start)
{
    MOZ_COUNT_CTOR(PCompositorParent);
}

PCompositorParent::~PCompositorParent()
{
    MOZ_COUNT_DTOR(PCompositorParent);
}

bool
PCompositorParent::Open(
        Channel::Transport* aTransport,
        ProcessHandle aOtherProcess,
        MessageLoop* aThread,
        AsyncChannel::Side aSide)
{
    mOtherProcess = aOtherProcess;
    return (mChannel).Open(aTransport, aThread, aSide);
}

bool
PCompositorParent::Open(
        AsyncChannel* aChannel,
        MessageLoop* aMessageLoop,
        AsyncChannel::Side aSide)
{
    mOtherProcess = 0;
    return (mChannel).Open(aChannel, aMessageLoop, aSide);
}

void
PCompositorParent::Close()
{
    (mChannel).Close();
}

void
PCompositorParent::SetReplyTimeoutMs(int32_t aTimeoutMs)
{
    (mChannel).SetReplyTimeoutMs(aTimeoutMs);
}

void
PCompositorParent::ManagedPGrallocBufferParent(InfallibleTArray<PGrallocBufferParent*>& aArr) const
{
    aArr = mManagedPGrallocBufferParent;
}

const InfallibleTArray<PGrallocBufferParent*>&
PCompositorParent::ManagedPGrallocBufferParent() const
{
    return mManagedPGrallocBufferParent;
}

void
PCompositorParent::ManagedPLayersParent(InfallibleTArray<PLayersParent*>& aArr) const
{
    aArr = mManagedPLayersParent;
}

const InfallibleTArray<PLayersParent*>&
PCompositorParent::ManagedPLayersParent() const
{
    return mManagedPLayersParent;
}

PCompositor::State
PCompositorParent::state()
{
    return mState;
}

int32_t
PCompositorParent::Register(ChannelListener* aRouted)
{
    int32_t tmp = (++(mLastRouteId));
    (mActorMap).AddWithID(aRouted, tmp);
    return tmp;
}

int32_t
PCompositorParent::RegisterID(
        ChannelListener* aRouted,
        int32_t aId)
{
    (mActorMap).AddWithID(aRouted, aId);
    return aId;
}

ChannelListener*
PCompositorParent::Lookup(int32_t aId)
{
    return (mActorMap).Lookup(aId);
}

void
PCompositorParent::Unregister(int32_t aId)
{
    return (mActorMap).Remove(aId);
}

void
PCompositorParent::RemoveManagee(
        int32_t aProtocolId,
        ChannelListener* aListener)
{
    switch (aProtocolId) {
    case PGrallocBufferMsgStart:
        {
            PGrallocBufferParent* actor = static_cast<PGrallocBufferParent*>(aListener);
            NS_ABORT_IF_FALSE(((mManagedPGrallocBufferParent).NoIndex) != ((mManagedPGrallocBufferParent).BinaryIndexOf(actor)), "actor not managed by this!");

            (mManagedPGrallocBufferParent).RemoveElementSorted(actor);
            DeallocPGrallocBuffer(actor);
            return;
        }
    case PLayersMsgStart:
        {
            PLayersParent* actor = static_cast<PLayersParent*>(aListener);
            NS_ABORT_IF_FALSE(((mManagedPLayersParent).NoIndex) != ((mManagedPLayersParent).BinaryIndexOf(actor)), "actor not managed by this!");

            (mManagedPLayersParent).RemoveElementSorted(actor);
            DeallocPLayers(actor);
            return;
        }
    default:
        {
            NS_RUNTIMEABORT("unreached");
            return;
        }
    }
}

Shmem::SharedMemory*
PCompositorParent::CreateSharedMemory(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        bool aUnsafe,
        Shmem::id_t* aId)
{
    nsAutoPtr<Shmem::SharedMemory> segment(Shmem::Alloc(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), aSize, aType, aUnsafe));
    if ((!(segment))) {
        return 0;
    }
    Shmem shmem(
            Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(),
            (segment).get(),
            (++(mLastShmemId)));
    Message* descriptor = (shmem).ShareTo(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), OtherProcess(), MSG_ROUTING_CONTROL);
    if ((!(descriptor))) {
        return 0;
    }
    if ((!((mChannel).Send(descriptor)))) {
    }
    (*(aId)) = (shmem).Id(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    (mShmemMap).AddWithID(segment, (*(aId)));
    return (segment).forget();
}

bool
PCompositorParent::AdoptSharedMemory(
        Shmem::SharedMemory* segment,
        Shmem::id_t* aId)
{
    Shmem shmem(
            Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(),
            segment,
            (++(mLastShmemId)));
    Message* descriptor = (shmem).ShareTo(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), OtherProcess(), MSG_ROUTING_CONTROL);
    if ((!(descriptor))) {
        return false;
    }
    if ((!((mChannel).Send(descriptor)))) {
    }
    (*(aId)) = (shmem).Id(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    (mShmemMap).AddWithID(segment, (*(aId)));
    (segment)->AddRef();
    return true;
}

Shmem::SharedMemory*
PCompositorParent::LookupSharedMemory(Shmem::id_t aId)
{
    return (mShmemMap).Lookup(aId);
}

bool
PCompositorParent::IsTrackingSharedMemory(Shmem::SharedMemory* segment)
{
    return (mShmemMap).HasData(segment);
}

bool
PCompositorParent::DestroySharedMemory(Shmem& shmem)
{
    Shmem::id_t aId = (shmem).Id(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    Shmem::SharedMemory* segment = LookupSharedMemory(aId);
    if ((!(segment))) {
        return false;
    }
    Message* descriptor = (shmem).UnshareFrom(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), OtherProcess(), MSG_ROUTING_CONTROL);

    (mShmemMap).Remove(aId);
    Shmem::Dealloc(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), segment);

    return (descriptor) && ((mChannel).Send(descriptor));
}

ProcessHandle
PCompositorParent::OtherProcess() const
{
    return mOtherProcess;
}

AsyncChannel*
PCompositorParent::GetIPCChannel()
{
    return (&(mChannel));
}

PCompositorParent::Result
PCompositorParent::OnMessageReceived(const Message& __msg)
{
    int32_t __route = (__msg).routing_id();
    if ((MSG_ROUTING_CONTROL) != (__route)) {
        ChannelListener* __routed = Lookup(__route);
        if ((!(__routed))) {
            return MsgRouteError;
        }
        return (__routed)->OnMessageReceived(__msg);
    }

    switch ((__msg).type()) {
    case PCompositor::Msg_MemoryPressure__ID:
        {
            (const_cast<Message&>(__msg)).set_name("PCompositor::Msg_MemoryPressure");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Msg_MemoryPressure*>((&(__msg))))->Log("[PCompositorParent] Received ", stderr);
            }

            if ((!(PCompositor::Transition(mState, Trigger(Trigger::Recv, PCompositor::Msg_MemoryPressure__ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            if ((!(RecvMemoryPressure()))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for MemoryPressure returned error code");
                return MsgProcessingError;
            }

            return MsgProcessed;
        }
    default:
        {
            return MsgNotKnown;
        }
    case SHMEM_CREATED_MESSAGE_TYPE:
        {
            Shmem::id_t id;
            nsAutoPtr<Shmem::SharedMemory> rawmem(Shmem::OpenExisting(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), __msg, (&(id)), true));
            if ((!(rawmem))) {
                return MsgPayloadError;
            }
            (mShmemMap).AddWithID((rawmem).forget(), id);

            return MsgProcessed;
        }
    case SHMEM_DESTROYED_MESSAGE_TYPE:
        {
            Shmem::id_t id;
            void* iter = 0;
            if ((!(IPC::ReadParam((&(__msg)), (&(iter)), (&(id)))))) {
                return MsgPayloadError;
            }
            (__msg).EndRead(iter);

            Shmem::SharedMemory* rawmem = LookupSharedMemory(id);
            if ((!(rawmem))) {
                return MsgValueError;
            }
            (mShmemMap).Remove(id);
            Shmem::Dealloc(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), rawmem);
            return MsgProcessed;
        }
    }
}

PCompositorParent::Result
PCompositorParent::OnMessageReceived(
        const Message& __msg,
        Message*& __reply)
{
    int32_t __route = (__msg).routing_id();
    if ((MSG_ROUTING_CONTROL) != (__route)) {
        ChannelListener* __routed = Lookup(__route);
        if ((!(__routed))) {
            return MsgRouteError;
        }
        return (__routed)->OnMessageReceived(__msg, __reply);
    }

    switch ((__msg).type()) {
    case PCompositor::Msg_WillStop__ID:
        {
            (const_cast<Message&>(__msg)).set_name("PCompositor::Msg_WillStop");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Msg_WillStop*>((&(__msg))))->Log("[PCompositorParent] Received ", stderr);
            }

            if ((!(PCompositor::Transition(mState, Trigger(Trigger::Recv, PCompositor::Msg_WillStop__ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            int32_t __id = MSG_ROUTING_CONTROL;
            if ((!(RecvWillStop()))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for WillStop returned error code");
                return MsgProcessingError;
            }

            __reply = new PCompositor::Reply_WillStop();

            (__reply)->set_routing_id(__id);
            (__reply)->set_sync();
            (__reply)->set_reply();

            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Reply_WillStop*>(__reply))->Log("[PCompositorParent] Sending reply ", stderr);
            }
            return MsgProcessed;
        }
    case PCompositor::Msg_Stop__ID:
        {
            (const_cast<Message&>(__msg)).set_name("PCompositor::Msg_Stop");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Msg_Stop*>((&(__msg))))->Log("[PCompositorParent] Received ", stderr);
            }

            if ((!(PCompositor::Transition(mState, Trigger(Trigger::Recv, PCompositor::Msg_Stop__ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            int32_t __id = MSG_ROUTING_CONTROL;
            if ((!(RecvStop()))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for Stop returned error code");
                return MsgProcessingError;
            }

            __reply = new PCompositor::Reply_Stop();

            (__reply)->set_routing_id(__id);
            (__reply)->set_sync();
            (__reply)->set_reply();

            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Reply_Stop*>(__reply))->Log("[PCompositorParent] Sending reply ", stderr);
            }
            return MsgProcessed;
        }
    case PCompositor::Msg_Pause__ID:
        {
            (const_cast<Message&>(__msg)).set_name("PCompositor::Msg_Pause");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Msg_Pause*>((&(__msg))))->Log("[PCompositorParent] Received ", stderr);
            }

            if ((!(PCompositor::Transition(mState, Trigger(Trigger::Recv, PCompositor::Msg_Pause__ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            int32_t __id = MSG_ROUTING_CONTROL;
            if ((!(RecvPause()))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for Pause returned error code");
                return MsgProcessingError;
            }

            __reply = new PCompositor::Reply_Pause();

            (__reply)->set_routing_id(__id);
            (__reply)->set_sync();
            (__reply)->set_reply();

            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Reply_Pause*>(__reply))->Log("[PCompositorParent] Sending reply ", stderr);
            }
            return MsgProcessed;
        }
    case PCompositor::Msg_Resume__ID:
        {
            (const_cast<Message&>(__msg)).set_name("PCompositor::Msg_Resume");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Msg_Resume*>((&(__msg))))->Log("[PCompositorParent] Received ", stderr);
            }

            if ((!(PCompositor::Transition(mState, Trigger(Trigger::Recv, PCompositor::Msg_Resume__ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            int32_t __id = MSG_ROUTING_CONTROL;
            if ((!(RecvResume()))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for Resume returned error code");
                return MsgProcessingError;
            }

            __reply = new PCompositor::Reply_Resume();

            (__reply)->set_routing_id(__id);
            (__reply)->set_sync();
            (__reply)->set_reply();

            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Reply_Resume*>(__reply))->Log("[PCompositorParent] Sending reply ", stderr);
            }
            return MsgProcessed;
        }
    case PCompositor::Msg_MakeSnapshot__ID:
        {
            (const_cast<Message&>(__msg)).set_name("PCompositor::Msg_MakeSnapshot");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Msg_MakeSnapshot*>((&(__msg))))->Log("[PCompositorParent] Received ", stderr);
            }

            void* __iter = 0;
            SurfaceDescriptor inSnapshot;

            if ((!(Read((&(inSnapshot)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            (__msg).EndRead(__iter);
            if ((!(PCompositor::Transition(mState, Trigger(Trigger::Recv, PCompositor::Msg_MakeSnapshot__ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            SurfaceDescriptor outSnapshot;
            int32_t __id = MSG_ROUTING_CONTROL;
            if ((!(RecvMakeSnapshot(inSnapshot, (&(outSnapshot)))))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for MakeSnapshot returned error code");
                return MsgProcessingError;
            }

            __reply = new PCompositor::Reply_MakeSnapshot();

            Write(outSnapshot, __reply);
            (__reply)->set_routing_id(__id);
            (__reply)->set_sync();
            (__reply)->set_reply();

            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Reply_MakeSnapshot*>(__reply))->Log("[PCompositorParent] Sending reply ", stderr);
            }
            return MsgProcessed;
        }
    case PCompositor::Msg_PLayersConstructor__ID:
        {
            (const_cast<Message&>(__msg)).set_name("PCompositor::Msg_PLayersConstructor");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Msg_PLayersConstructor*>((&(__msg))))->Log("[PCompositorParent] Received ", stderr);
            }

            void* __iter = 0;
            ActorHandle __handle;
            PLayersParent* actor;
            LayersBackend backendHint;
            uint64_t id;

            if ((!(Read((&(__handle)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            if ((!(Read((&(backendHint)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            if ((!(Read((&(id)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            (__msg).EndRead(__iter);
            if ((!(PCompositor::Transition(mState, Trigger(Trigger::Recv, PCompositor::Msg_PLayersConstructor__ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            LayersBackend backend;
            int32_t maxTextureSize;
            actor = AllocPLayers(backendHint, id, (&(backend)), (&(maxTextureSize)));
            if ((!(actor))) {
                return MsgValueError;
            }
            (actor)->mId = RegisterID(actor, (__handle).mId);
            (actor)->mManager = this;
            (actor)->mChannel = (&(mChannel));
            (mManagedPLayersParent).InsertElementSorted(actor);
            (actor)->mState = mozilla::layers::PLayers::__Start;

            int32_t __id = MSG_ROUTING_CONTROL;
            if ((!(RecvPLayersConstructor(actor, backendHint, id, (&(backend)), (&(maxTextureSize)))))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for PLayers returned error code");
                return MsgProcessingError;
            }
            __reply = new PCompositor::Reply_PLayersConstructor();

            Write(backend, __reply);
            Write(maxTextureSize, __reply);
            (__reply)->set_routing_id(__id);
            (__reply)->set_sync();
            (__reply)->set_reply();

            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Reply_PLayersConstructor*>(__reply))->Log("[PCompositorParent] Sending reply ", stderr);
            }

            return MsgProcessed;
        }
    case PCompositor::Msg_PGrallocBufferConstructor__ID:
        {
            (const_cast<Message&>(__msg)).set_name("PCompositor::Msg_PGrallocBufferConstructor");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Msg_PGrallocBufferConstructor*>((&(__msg))))->Log("[PCompositorParent] Received ", stderr);
            }

            void* __iter = 0;
            ActorHandle __handle;
            PGrallocBufferParent* actor;
            gfxIntSize size;
            uint32_t format;
            uint32_t usage;

            if ((!(Read((&(__handle)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            if ((!(Read((&(size)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            if ((!(Read((&(format)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            if ((!(Read((&(usage)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            (__msg).EndRead(__iter);
            if ((!(PCompositor::Transition(mState, Trigger(Trigger::Recv, PCompositor::Msg_PGrallocBufferConstructor__ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            MaybeMagicGrallocBufferHandle handle;
            actor = AllocPGrallocBuffer(size, format, usage, (&(handle)));
            if ((!(actor))) {
                return MsgValueError;
            }
            (actor)->mId = RegisterID(actor, (__handle).mId);
            (actor)->mManager = this;
            (actor)->mChannel = (&(mChannel));
            (mManagedPGrallocBufferParent).InsertElementSorted(actor);
            (actor)->mState = mozilla::layers::PGrallocBuffer::__Start;

            int32_t __id = MSG_ROUTING_CONTROL;
            if ((!(RecvPGrallocBufferConstructor(actor, size, format, usage, (&(handle)))))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for PGrallocBuffer returned error code");
                return MsgProcessingError;
            }
            __reply = new PCompositor::Reply_PGrallocBufferConstructor();

            Write(handle, __reply);
            (__reply)->set_routing_id(__id);
            (__reply)->set_sync();
            (__reply)->set_reply();

            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PCompositor::Reply_PGrallocBufferConstructor*>(__reply))->Log("[PCompositorParent] Sending reply ", stderr);
            }

            return MsgProcessed;
        }
    default:
        {
            return MsgNotKnown;
        }
    }
}

PCompositorParent::Result
PCompositorParent::OnCallReceived(
        const Message& __msg,
        Message*& __reply)
{
    int32_t __route = (__msg).routing_id();
    if ((MSG_ROUTING_CONTROL) != (__route)) {
        ChannelListener* __routed = Lookup(__route);
        if ((!(__routed))) {
            return MsgRouteError;
        }
        return (__routed)->OnCallReceived(__msg, __reply);
    }

    return MsgNotKnown;
}

void
PCompositorParent::OnProcessingError(Result code)
{
    return ProcessingError(code);
}

int32_t
PCompositorParent::GetProtocolTypeId()
{
    return PCompositorMsgStart;
}

bool
PCompositorParent::OnReplyTimeout()
{
    return ShouldContinueFromReplyTimeout();
}

void
PCompositorParent::OnEnteredCxxStack()
{
    return EnteredCxxStack();
}

void
PCompositorParent::OnExitedCxxStack()
{
    return ExitedCxxStack();
}

void
PCompositorParent::OnEnteredCall()
{
    return EnteredCall();
}

void
PCompositorParent::OnExitedCall()
{
    return ExitedCall();
}

bool
PCompositorParent::IsOnCxxStack() const
{
    return (mChannel).IsOnCxxStack();
}

void
PCompositorParent::FlushPendingRPCQueue()
{
    ((this)->mChannel).FlushPendingRPCQueue();
}

void
PCompositorParent::OnChannelClose()
{
    DestroySubtree(NormalShutdown);
    DeallocSubtree();
    DeallocShmems();
}

void
PCompositorParent::OnChannelError()
{
    DestroySubtree(AbnormalShutdown);
    DeallocSubtree();
    DeallocShmems();
}

void
PCompositorParent::OnChannelConnected(int32_t pid)
{
}

bool
PCompositorParent::AllocShmem(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        Shmem* aMem)
{
    Shmem::id_t aId;
    nsAutoPtr<Shmem::SharedMemory> rawmem(CreateSharedMemory(aSize, aType, false, (&(aId))));
    if ((!(rawmem))) {
        return false;
    }

    (*(aMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), (rawmem).forget(), aId);
    return true;
}

bool
PCompositorParent::AllocUnsafeShmem(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        Shmem* aMem)
{
    Shmem::id_t aId;
    nsAutoPtr<Shmem::SharedMemory> rawmem(CreateSharedMemory(aSize, aType, true, (&(aId))));
    if ((!(rawmem))) {
        return false;
    }

    (*(aMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), (rawmem).forget(), aId);
    return true;
}

bool
PCompositorParent::AdoptShmem(
        Shmem& aMem,
        Shmem* aOutMem)
{
    Shmem::SharedMemory* rawmem = (aMem).Segment(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    if (((!(rawmem))) || (IsTrackingSharedMemory(rawmem))) {
        NS_RUNTIMEABORT("bad Shmem");
    }

    Shmem::id_t aId;
    if ((!(AdoptSharedMemory(rawmem, (&(aId)))))) {
        return false;
    }

    (*(aOutMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), rawmem, aId);
    return true;
}

bool
PCompositorParent::DeallocShmem(Shmem& aMem)
{
    bool ok = DestroySharedMemory(aMem);
    (aMem).forget(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    return ok;
}

void
PCompositorParent::ProcessNativeEventsInRPCCall()
{
#ifdef OS_WIN
    (mChannel).ProcessNativeEventsInRPCCall();
#else 
    NS_RUNTIMEABORT("This method is Windows-only");
#endif 
}

void
PCompositorParent::SetOtherProcess(ProcessHandle aOtherProcess)
{
    mOtherProcess = aOtherProcess;
}

base::ProcessId
PCompositorParent::OtherSidePID() const
{
    return base::GetProcId(mOtherProcess);
}

bool
PCompositorParent::TakeMinidump(
        nsIFile** aDump,
        uint32_t* aSequence) const
{
#ifdef MOZ_CRASHREPORTER
    return XRE_TakeMinidumpForChild(OtherSidePID(), aDump, aSequence);
#else 
    return false;
#endif 
}

bool
PCompositorParent::BlockChild()
{
    return (mChannel).BlockChild();
}

bool
PCompositorParent::UnblockChild()
{
    return (mChannel).UnblockChild();
}

void
PCompositorParent::FatalError(const char* const msg) const
{
    // Virtual method to prevent inlining.
    // This give us better error reporting.
    // See bug 589371

    NS_ERROR("IPDL error:");
    NS_ERROR(msg);
    mozilla::ipc::ProtocolErrorBreakpoint(msg);

    NS_ERROR("[PCompositorParent] killing child side as a result");

    if ((!(base::KillProcess(OtherProcess(), base::PROCESS_END_KILLED_BY_USER, false)))) {
        NS_ERROR("  may have failed to kill child!");
    }
}

void
PCompositorParent::DestroySubtree(ActorDestroyReason why)
{
    ActorDestroyReason subtreewhy = (((why) == (Deletion)) || ((why) == (FailedConstructor)) ? AncestorDeletion : why);

    {
        // Recursively shutting down PGrallocBuffer kids
        InfallibleTArray<PGrallocBufferParent*> kids(mManagedPGrallocBufferParent);
        for (uint32_t i = 0; (i) < ((kids).Length()); (++(i))) {
            (kids[i])->DestroySubtree(subtreewhy);
        }
    }
    {
        // Recursively shutting down PLayers kids
        InfallibleTArray<PLayersParent*> kids(mManagedPLayersParent);
        for (uint32_t i = 0; (i) < ((kids).Length()); (++(i))) {
            (kids[i])->DestroySubtree(subtreewhy);
        }
    }

    // Finally, destroy "us".
    ActorDestroy(why);
}

void
PCompositorParent::DeallocSubtree()
{
    {
        // Recursively deleting PGrallocBuffer kids
        InfallibleTArray<PGrallocBufferParent*>& kids = mManagedPGrallocBufferParent;
        for (uint32_t i = 0; (i) < ((kids).Length()); (++(i))) {
            (kids[i])->DeallocSubtree();
        }

        for (uint32_t i = 0; (i) < ((kids).Length()); (++(i))) {
            DeallocPGrallocBuffer(kids[i]);
        }
        (mManagedPGrallocBufferParent).Clear();
    }
    {
        // Recursively deleting PLayers kids
        InfallibleTArray<PLayersParent*>& kids = mManagedPLayersParent;
        for (uint32_t i = 0; (i) < ((kids).Length()); (++(i))) {
            (kids[i])->DeallocSubtree();
        }

        for (uint32_t i = 0; (i) < ((kids).Length()); (++(i))) {
            DeallocPLayers(kids[i]);
        }
        (mManagedPLayersParent).Clear();
    }
}

void
PCompositorParent::DeallocShmems()
{
    for (IDMap<SharedMemory>::const_iterator cit = (mShmemMap).begin(); (cit) != ((mShmemMap).end()); (++(cit))) {
        Shmem::Dealloc(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), (cit)->second);
    }
    (mShmemMap).Clear();
}

void
PCompositorParent::Write(
        const SurfaceDescriptor& __v,
        Message* __msg)
{
    typedef SurfaceDescriptor __type;
    Write(int((__v).type()), __msg);

    switch ((__v).type()) {
    case __type::TShmem:
        {
            Write((__v).get_Shmem(), __msg);
            return;
        }
    case __type::TSurfaceDescriptorD3D10:
        {
            Write((__v).get_SurfaceDescriptorD3D10(), __msg);
            return;
        }
    case __type::TSurfaceDescriptorGralloc:
        {
            Write((__v).get_SurfaceDescriptorGralloc(), __msg);
            return;
        }
    case __type::TSurfaceDescriptorX11:
        {
            Write((__v).get_SurfaceDescriptorX11(), __msg);
            return;
        }
    case __type::TSharedTextureDescriptor:
        {
            Write((__v).get_SharedTextureDescriptor(), __msg);
            return;
        }
    default:
        {
            NS_RUNTIMEABORT("unknown union type");
            return;
        }
    }
}

bool
PCompositorParent::Read(
        SurfaceDescriptor* __v,
        const Message* __msg,
        void** __iter)
{
    typedef SurfaceDescriptor __type;
    int type;
    if ((!(Read((&(type)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }

    switch (type) {
    case __type::TShmem:
        {
            Shmem tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_Shmem())), __msg, __iter);
        }
    case __type::TSurfaceDescriptorD3D10:
        {
            SurfaceDescriptorD3D10 tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_SurfaceDescriptorD3D10())), __msg, __iter);
        }
    case __type::TSurfaceDescriptorGralloc:
        {
            SurfaceDescriptorGralloc tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_SurfaceDescriptorGralloc())), __msg, __iter);
        }
    case __type::TSurfaceDescriptorX11:
        {
            SurfaceDescriptorX11 tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_SurfaceDescriptorX11())), __msg, __iter);
        }
    case __type::TSharedTextureDescriptor:
        {
            SharedTextureDescriptor tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_SharedTextureDescriptor())), __msg, __iter);
        }
    default:
        {
            mozilla::ipc::ProtocolErrorBreakpoint("unknown union type");
            return false;
        }
    }
}

void
PCompositorParent::Write(
        Shmem& __v,
        Message* __msg)
{
    IPC::WriteParam(__msg, __v);
    (__v).RevokeRights(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    (__v).forget(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
}

bool
PCompositorParent::Read(
        Shmem* __v,
        const Message* __msg,
        void** __iter)
{
    Shmem tmp;
    if ((!(IPC::ReadParam(__msg, __iter, (&(tmp)))))) {
        return false;
    }

    Shmem::id_t shmemid = (tmp).Id(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    Shmem::SharedMemory* rawmem = LookupSharedMemory(shmemid);
    if (rawmem) {
        (*(__v)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), rawmem, shmemid);
        return true;
    }
    return false;
}

void
PCompositorParent::Write(
        PGrallocBufferParent* __v,
        Message* __msg,
        bool __nullable)
{
    int32_t id;
    if ((!(__v))) {
        if ((!(__nullable))) {
            NS_RUNTIMEABORT("NULL actor value passed to non-nullable param");
        }
        id = 0;
    }
    else {
        id = (__v)->mId;
        if ((1) == (id)) {
            NS_RUNTIMEABORT("actor has been |delete|d");
        }
    }

    Write(id, __msg);
}

bool
PCompositorParent::Read(
        PGrallocBufferParent** __v,
        const Message* __msg,
        void** __iter,
        bool __nullable)
{
    int32_t id;
    if ((!(Read((&(id)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if (((1) == (id)) || (((0) == (id)) && ((!(__nullable))))) {
        mozilla::ipc::ProtocolErrorBreakpoint("bad ID for PCompositor");
        return false;
    }

    if ((0) == (id)) {
        (*(__v)) = 0;
        return true;
    }

    ChannelListener* listener = Lookup(id);
    if ((!(listener))) {
        mozilla::ipc::ProtocolErrorBreakpoint("could not look up PGrallocBuffer");
        return false;
    }

    if ((PGrallocBufferMsgStart) != ((listener)->GetProtocolTypeId())) {
        mozilla::ipc::ProtocolErrorBreakpoint("actor that should be of type PGrallocBuffer has different type");
        return false;
    }

    (*(__v)) = static_cast<PGrallocBufferParent*>(listener);
    return true;
}

void
PCompositorParent::Write(
        const MaybeMagicGrallocBufferHandle& __v,
        Message* __msg)
{
    typedef MaybeMagicGrallocBufferHandle __type;
    Write(int((__v).type()), __msg);

    switch ((__v).type()) {
    case __type::TMagicGrallocBufferHandle:
        {
            Write((__v).get_MagicGrallocBufferHandle(), __msg);
            return;
        }
    case __type::Tnull_t:
        {
            Write((__v).get_null_t(), __msg);
            return;
        }
    default:
        {
            NS_RUNTIMEABORT("unknown union type");
            return;
        }
    }
}

bool
PCompositorParent::Read(
        MaybeMagicGrallocBufferHandle* __v,
        const Message* __msg,
        void** __iter)
{
    typedef MaybeMagicGrallocBufferHandle __type;
    int type;
    if ((!(Read((&(type)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }

    switch (type) {
    case __type::TMagicGrallocBufferHandle:
        {
            MagicGrallocBufferHandle tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_MagicGrallocBufferHandle())), __msg, __iter);
        }
    case __type::Tnull_t:
        {
            null_t tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_null_t())), __msg, __iter);
        }
    default:
        {
            mozilla::ipc::ProtocolErrorBreakpoint("unknown union type");
            return false;
        }
    }
}

void
PCompositorParent::Write(
        PLayersParent* __v,
        Message* __msg,
        bool __nullable)
{
    int32_t id;
    if ((!(__v))) {
        if ((!(__nullable))) {
            NS_RUNTIMEABORT("NULL actor value passed to non-nullable param");
        }
        id = 0;
    }
    else {
        id = (__v)->mId;
        if ((1) == (id)) {
            NS_RUNTIMEABORT("actor has been |delete|d");
        }
    }

    Write(id, __msg);
}

bool
PCompositorParent::Read(
        PLayersParent** __v,
        const Message* __msg,
        void** __iter,
        bool __nullable)
{
    int32_t id;
    if ((!(Read((&(id)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if (((1) == (id)) || (((0) == (id)) && ((!(__nullable))))) {
        mozilla::ipc::ProtocolErrorBreakpoint("bad ID for PCompositor");
        return false;
    }

    if ((0) == (id)) {
        (*(__v)) = 0;
        return true;
    }

    ChannelListener* listener = Lookup(id);
    if ((!(listener))) {
        mozilla::ipc::ProtocolErrorBreakpoint("could not look up PLayers");
        return false;
    }

    if ((PLayersMsgStart) != ((listener)->GetProtocolTypeId())) {
        mozilla::ipc::ProtocolErrorBreakpoint("actor that should be of type PLayers has different type");
        return false;
    }

    (*(__v)) = static_cast<PLayersParent*>(listener);
    return true;
}

void
PCompositorParent::Write(
        const SurfaceDescriptorD3D10& __v,
        Message* __msg)
{
    Write((__v).handle(), __msg);
}

bool
PCompositorParent::Read(
        SurfaceDescriptorD3D10* __v,
        const Message* __msg,
        void** __iter)
{
    if ((!(Read((&((__v)->handle())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    return true;
}

void
PCompositorParent::Write(
        const SurfaceDescriptorGralloc& __v,
        Message* __msg)
{
    Write((__v).bufferParent(), __msg, false);
    // skipping actor field that's meaningless on this side
    Write((__v).external(), __msg);
}

bool
PCompositorParent::Read(
        SurfaceDescriptorGralloc* __v,
        const Message* __msg,
        void** __iter)
{
    if ((!(Read((&((__v)->bufferParent())), __msg, __iter, false)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    // skipping actor field that's meaningless on this side
    if ((!(Read((&((__v)->external())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    return true;
}

void
PCompositorParent::Write(
        const SharedTextureDescriptor& __v,
        Message* __msg)
{
    Write((__v).shareType(), __msg);
    Write((__v).handle(), __msg);
    Write((__v).size(), __msg);
    Write((__v).inverted(), __msg);
}

bool
PCompositorParent::Read(
        SharedTextureDescriptor* __v,
        const Message* __msg,
        void** __iter)
{
    if ((!(Read((&((__v)->shareType())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->handle())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->size())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->inverted())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    return true;
}



} // namespace layers
} // namespace mozilla
