//
// Automatically generated by ipdlc.
// Edit at your own risk
//


#include "mozilla/dom/indexedDB/PIndexedDBIndexChild.h"

#include "mozilla/dom/PBlobChild.h"
#include "mozilla/dom/indexedDB/PIndexedDBCursorChild.h"
#include "mozilla/dom/indexedDB/PIndexedDBObjectStoreChild.h"
#include "mozilla/dom/indexedDB/PIndexedDBRequestChild.h"

typedef IPC::Message Message;
typedef mozilla::ipc::RPCChannel Channel;
typedef mozilla::ipc::RPCChannel::RPCListener ChannelListener;
typedef base::ProcessHandle ProcessHandle;
typedef mozilla::ipc::AsyncChannel AsyncChannel;
typedef mozilla::ipc::SharedMemory SharedMemory;
typedef mozilla::ipc::Trigger Trigger;
typedef mozilla::ipc::ActorHandle ActorHandle;
typedef mozilla::dom::indexedDB::ipc::FIXME_Bug_521898_index::CountParams CountParams;
typedef mozilla::dom::indexedDB::IDBCursor::Direction Direction;
typedef mozilla::ipc::FileDescriptor FileDescriptor;
typedef mozilla::dom::indexedDB::ipc::GetAllKeysParams GetAllKeysParams;
typedef mozilla::dom::indexedDB::ipc::FIXME_Bug_521898_index::GetAllParams GetAllParams;
typedef mozilla::dom::indexedDB::ipc::GetKeyParams GetKeyParams;
typedef mozilla::dom::indexedDB::ipc::FIXME_Bug_521898_index::GetParams GetParams;
typedef mozilla::dom::indexedDB::ipc::IndexCursorConstructorParams IndexCursorConstructorParams;
typedef mozilla::dom::indexedDB::ipc::IndexRequestParams IndexRequestParams;
typedef mozilla::dom::indexedDB::Key Key;
typedef mozilla::dom::indexedDB::ipc::FIXME_Bug_521898_index::KeyRange KeyRange;
typedef mozilla::dom::indexedDB::ipc::FIXME_Bug_521898_index::OpenCursorParams OpenCursorParams;
typedef mozilla::dom::indexedDB::ipc::OpenKeyCursorParams OpenKeyCursorParams;
typedef mozilla::dom::indexedDB::ipc::FIXME_Bug_521898_index::OptionalKeyRange OptionalKeyRange;
typedef mozilla::dom::indexedDB::ipc::OptionalStructuredCloneReadInfo OptionalStructuredCloneReadInfo;
typedef mozilla::dom::indexedDB::SerializedStructuredCloneReadInfo SerializedStructuredCloneReadInfo;
typedef mozilla::ipc::Shmem Shmem;
typedef mozilla::void_t void_t;
using mozilla::dom::PBlobChild;
using mozilla::dom::indexedDB::PIndexedDBCursorChild;
using mozilla::dom::indexedDB::PIndexedDBObjectStoreChild;
using mozilla::dom::indexedDB::PIndexedDBRequestChild;

namespace mozilla {
namespace dom {
namespace indexedDB {


bool
PIndexedDBIndexChild::RecvPIndexedDBCursorConstructor(
        PIndexedDBCursorChild* actor,
        const IndexCursorConstructorParams& params)
{
    return true;
}

void
PIndexedDBIndexChild::ActorDestroy(ActorDestroyReason why)
{
}

PIndexedDBIndexChild::PIndexedDBIndexChild() :
    mId(0),
    mState(PIndexedDBIndex::__Dead)
{
    MOZ_COUNT_CTOR(PIndexedDBIndexChild);
}

PIndexedDBIndexChild::~PIndexedDBIndexChild()
{
    MOZ_COUNT_DTOR(PIndexedDBIndexChild);
}

PIndexedDBObjectStoreChild*
PIndexedDBIndexChild::Manager() const
{
    return static_cast<PIndexedDBObjectStoreChild*>(mManager);
}

void
PIndexedDBIndexChild::ManagedPIndexedDBCursorChild(InfallibleTArray<PIndexedDBCursorChild*>& aArr) const
{
    aArr = mManagedPIndexedDBCursorChild;
}

const InfallibleTArray<PIndexedDBCursorChild*>&
PIndexedDBIndexChild::ManagedPIndexedDBCursorChild() const
{
    return mManagedPIndexedDBCursorChild;
}

void
PIndexedDBIndexChild::ManagedPIndexedDBRequestChild(InfallibleTArray<PIndexedDBRequestChild*>& aArr) const
{
    aArr = mManagedPIndexedDBRequestChild;
}

const InfallibleTArray<PIndexedDBRequestChild*>&
PIndexedDBIndexChild::ManagedPIndexedDBRequestChild() const
{
    return mManagedPIndexedDBRequestChild;
}

PIndexedDBIndex::State
PIndexedDBIndexChild::state()
{
    return mState;
}

bool
PIndexedDBIndexChild::Send__delete__(PIndexedDBIndexChild* actor)
{
    if ((!(actor))) {
        return false;
    }

    if ((!(actor))) {
        return false;
    }

    PIndexedDBIndex::Msg___delete__* __msg = new PIndexedDBIndex::Msg___delete__();

    (actor)->Write(actor, __msg, false);

    (__msg)->set_routing_id((actor)->mId);


    if (mozilla::ipc::LoggingEnabled()) {
        (__msg)->Log("[PIndexedDBIndexChild] Sending ", stderr);
    }
    if ((!(PIndexedDBIndex::Transition((actor)->mState, Trigger(Trigger::Recv, PIndexedDBIndex::Msg___delete____ID), (&((actor)->mState)))))) {
        NS_WARNING("bad state transition!");
    }

    bool __sendok = ((actor)->mChannel)->Send(__msg);

    (actor)->DestroySubtree(Deletion);
    (actor)->DeallocSubtree();
    ((actor)->mManager)->RemoveManagee(PIndexedDBIndexMsgStart, actor);
    return __sendok;
}

PIndexedDBRequestChild*
PIndexedDBIndexChild::SendPIndexedDBRequestConstructor(const IndexRequestParams& params)
{
    return SendPIndexedDBRequestConstructor(AllocPIndexedDBRequest(params), params);
}

PIndexedDBRequestChild*
PIndexedDBIndexChild::SendPIndexedDBRequestConstructor(
        PIndexedDBRequestChild* actor,
        const IndexRequestParams& params)
{
    if ((!(actor))) {
        return 0;
    }
    (actor)->mId = Register(actor);
    (actor)->mManager = this;
    (actor)->mChannel = mChannel;
    (mManagedPIndexedDBRequestChild).InsertElementSorted(actor);
    (actor)->mState = mozilla::dom::indexedDB::PIndexedDBRequest::__Start;

    PIndexedDBIndex::Msg_PIndexedDBRequestConstructor* __msg = new PIndexedDBIndex::Msg_PIndexedDBRequestConstructor();

    Write(actor, __msg, false);
    Write(params, __msg);

    (__msg)->set_routing_id(mId);


    if (mozilla::ipc::LoggingEnabled()) {
        (__msg)->Log("[PIndexedDBIndexChild] Sending ", stderr);
    }
    if ((!(PIndexedDBIndex::Transition(mState, Trigger(Trigger::Recv, PIndexedDBIndex::Msg_PIndexedDBRequestConstructor__ID), (&(mState)))))) {
        NS_WARNING("bad state transition!");
    }

    bool __sendok = (mChannel)->Send(__msg);
    if ((!(__sendok))) {
        (actor)->DestroySubtree(FailedConstructor);
        (actor)->DeallocSubtree();
        ((actor)->mManager)->RemoveManagee(PIndexedDBRequestMsgStart, actor);
        return 0;
    }
    return actor;
}

int32_t
PIndexedDBIndexChild::Register(ChannelListener* aRouted)
{
    return (mManager)->Register(aRouted);
}

int32_t
PIndexedDBIndexChild::RegisterID(
        ChannelListener* aRouted,
        int32_t aId)
{
    return (mManager)->RegisterID(aRouted, aId);
}

ChannelListener*
PIndexedDBIndexChild::Lookup(int32_t aId)
{
    return (mManager)->Lookup(aId);
}

void
PIndexedDBIndexChild::Unregister(int32_t aId)
{
    return (mManager)->Unregister(aId);
}

void
PIndexedDBIndexChild::RemoveManagee(
        int32_t aProtocolId,
        ChannelListener* aListener)
{
    switch (aProtocolId) {
    case PIndexedDBCursorMsgStart:
        {
            PIndexedDBCursorChild* actor = static_cast<PIndexedDBCursorChild*>(aListener);
            NS_ABORT_IF_FALSE(((mManagedPIndexedDBCursorChild).NoIndex) != ((mManagedPIndexedDBCursorChild).BinaryIndexOf(actor)), "actor not managed by this!");

            (mManagedPIndexedDBCursorChild).RemoveElementSorted(actor);
            DeallocPIndexedDBCursor(actor);
            return;
        }
    case PIndexedDBRequestMsgStart:
        {
            PIndexedDBRequestChild* actor = static_cast<PIndexedDBRequestChild*>(aListener);
            NS_ABORT_IF_FALSE(((mManagedPIndexedDBRequestChild).NoIndex) != ((mManagedPIndexedDBRequestChild).BinaryIndexOf(actor)), "actor not managed by this!");

            (mManagedPIndexedDBRequestChild).RemoveElementSorted(actor);
            DeallocPIndexedDBRequest(actor);
            return;
        }
    default:
        {
            NS_RUNTIMEABORT("unreached");
            return;
        }
    }
}

Shmem::SharedMemory*
PIndexedDBIndexChild::CreateSharedMemory(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        bool aUnsafe,
        Shmem::id_t* aId)
{
    return (mManager)->CreateSharedMemory(aSize, aType, aUnsafe, aId);
}

bool
PIndexedDBIndexChild::AdoptSharedMemory(
        Shmem::SharedMemory* segment,
        Shmem::id_t* aId)
{
    return (mManager)->AdoptSharedMemory(segment, aId);
}

Shmem::SharedMemory*
PIndexedDBIndexChild::LookupSharedMemory(Shmem::id_t aId)
{
    return (mManager)->LookupSharedMemory(aId);
}

bool
PIndexedDBIndexChild::IsTrackingSharedMemory(Shmem::SharedMemory* segment)
{
    return (mManager)->IsTrackingSharedMemory(segment);
}

bool
PIndexedDBIndexChild::DestroySharedMemory(Shmem& shmem)
{
    return (mManager)->DestroySharedMemory(shmem);
}

ProcessHandle
PIndexedDBIndexChild::OtherProcess() const
{
    return (mManager)->OtherProcess();
}

AsyncChannel*
PIndexedDBIndexChild::GetIPCChannel()
{
    return mChannel;
}

PIndexedDBIndexChild::Result
PIndexedDBIndexChild::OnMessageReceived(const Message& __msg)
{
    switch ((__msg).type()) {
    case PIndexedDBIndex::Reply___delete____ID:
        {
            return MsgProcessed;
        }
    case PIndexedDBIndex::Reply_PIndexedDBRequestConstructor__ID:
        {
            return MsgProcessed;
        }
    case PIndexedDBIndex::Msg_PIndexedDBCursorConstructor__ID:
        {
            (const_cast<Message&>(__msg)).set_name("PIndexedDBIndex::Msg_PIndexedDBCursorConstructor");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PIndexedDBIndex::Msg_PIndexedDBCursorConstructor*>((&(__msg))))->Log("[PIndexedDBIndexChild] Received ", stderr);
            }

            void* __iter = 0;
            ActorHandle __handle;
            PIndexedDBCursorChild* actor;
            IndexCursorConstructorParams params;

            if ((!(Read((&(__handle)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            if ((!(Read((&(params)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            (__msg).EndRead(__iter);
            if ((!(PIndexedDBIndex::Transition(mState, Trigger(Trigger::Send, PIndexedDBIndex::Msg_PIndexedDBCursorConstructor__ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            actor = AllocPIndexedDBCursor(params);
            if ((!(actor))) {
                return MsgValueError;
            }
            (actor)->mId = RegisterID(actor, (__handle).mId);
            (actor)->mManager = this;
            (actor)->mChannel = mChannel;
            (mManagedPIndexedDBCursorChild).InsertElementSorted(actor);
            (actor)->mState = mozilla::dom::indexedDB::PIndexedDBCursor::__Start;

            if ((!(RecvPIndexedDBCursorConstructor(actor, params)))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for PIndexedDBCursor returned error code");
                return MsgProcessingError;
            }

            return MsgProcessed;
        }
    default:
        {
            return MsgNotKnown;
        }
    }
}

PIndexedDBIndexChild::Result
PIndexedDBIndexChild::OnMessageReceived(
        const Message& __msg,
        Message*& __reply)
{
    return MsgNotKnown;
}

PIndexedDBIndexChild::Result
PIndexedDBIndexChild::OnCallReceived(
        const Message& __msg,
        Message*& __reply)
{
    return MsgNotKnown;
}

void
PIndexedDBIndexChild::OnProcessingError(Result code)
{
    NS_RUNTIMEABORT("`OnProcessingError' called on non-toplevel actor");
}

int32_t
PIndexedDBIndexChild::GetProtocolTypeId()
{
    return PIndexedDBIndexMsgStart;
}

bool
PIndexedDBIndexChild::OnReplyTimeout()
{
    NS_RUNTIMEABORT("`OnReplyTimeout' called on non-toplevel actor");
    return false;
}

void
PIndexedDBIndexChild::OnChannelClose()
{
    NS_RUNTIMEABORT("`OnClose' called on non-toplevel actor");
}

void
PIndexedDBIndexChild::OnChannelError()
{
    NS_RUNTIMEABORT("`OnError' called on non-toplevel actor");
}

void
PIndexedDBIndexChild::OnChannelConnected(int32_t pid)
{
    NS_RUNTIMEABORT("'OnConnected' called on non-toplevel actor");
}

bool
PIndexedDBIndexChild::AllocShmem(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        Shmem* aMem)
{
    Shmem::id_t aId;
    nsAutoPtr<Shmem::SharedMemory> rawmem(CreateSharedMemory(aSize, aType, false, (&(aId))));
    if ((!(rawmem))) {
        return false;
    }

    (*(aMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), (rawmem).forget(), aId);
    return true;
}

bool
PIndexedDBIndexChild::AllocUnsafeShmem(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        Shmem* aMem)
{
    Shmem::id_t aId;
    nsAutoPtr<Shmem::SharedMemory> rawmem(CreateSharedMemory(aSize, aType, true, (&(aId))));
    if ((!(rawmem))) {
        return false;
    }

    (*(aMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), (rawmem).forget(), aId);
    return true;
}

bool
PIndexedDBIndexChild::AdoptShmem(
        Shmem& aMem,
        Shmem* aOutMem)
{
    Shmem::SharedMemory* rawmem = (aMem).Segment(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    if (((!(rawmem))) || (IsTrackingSharedMemory(rawmem))) {
        NS_RUNTIMEABORT("bad Shmem");
    }

    Shmem::id_t aId;
    if ((!(AdoptSharedMemory(rawmem, (&(aId)))))) {
        return false;
    }

    (*(aOutMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), rawmem, aId);
    return true;
}

bool
PIndexedDBIndexChild::DeallocShmem(Shmem& aMem)
{
    bool ok = DestroySharedMemory(aMem);
    (aMem).forget(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    return ok;
}

void
PIndexedDBIndexChild::FatalError(const char* const msg) const
{
    // Virtual method to prevent inlining.
    // This give us better error reporting.
    // See bug 589371

    NS_ERROR("IPDL error:");
    NS_ERROR(msg);
    mozilla::ipc::ProtocolErrorBreakpoint(msg);

    NS_RUNTIMEABORT("[PIndexedDBIndexChild] abort()ing as a result");
}

void
PIndexedDBIndexChild::DestroySubtree(ActorDestroyReason why)
{
    // Unregister from our manager.
    Unregister(mId);
    mId = 1;

    ActorDestroyReason subtreewhy = (((why) == (Deletion)) || ((why) == (FailedConstructor)) ? AncestorDeletion : why);

    {
        // Recursively shutting down PIndexedDBCursor kids
        InfallibleTArray<PIndexedDBCursorChild*> kids(mManagedPIndexedDBCursorChild);
        for (uint32_t i = 0; (i) < ((kids).Length()); (++(i))) {
            (kids[i])->DestroySubtree(subtreewhy);
        }
    }
    {
        // Recursively shutting down PIndexedDBRequest kids
        InfallibleTArray<PIndexedDBRequestChild*> kids(mManagedPIndexedDBRequestChild);
        for (uint32_t i = 0; (i) < ((kids).Length()); (++(i))) {
            (kids[i])->DestroySubtree(subtreewhy);
        }
    }

    // Finally, destroy "us".
    ActorDestroy(why);
}

void
PIndexedDBIndexChild::DeallocSubtree()
{
    {
        // Recursively deleting PIndexedDBCursor kids
        InfallibleTArray<PIndexedDBCursorChild*>& kids = mManagedPIndexedDBCursorChild;
        for (uint32_t i = 0; (i) < ((kids).Length()); (++(i))) {
            (kids[i])->DeallocSubtree();
        }

        for (uint32_t i = 0; (i) < ((kids).Length()); (++(i))) {
            DeallocPIndexedDBCursor(kids[i]);
        }
        (mManagedPIndexedDBCursorChild).Clear();
    }
    {
        // Recursively deleting PIndexedDBRequest kids
        InfallibleTArray<PIndexedDBRequestChild*>& kids = mManagedPIndexedDBRequestChild;
        for (uint32_t i = 0; (i) < ((kids).Length()); (++(i))) {
            (kids[i])->DeallocSubtree();
        }

        for (uint32_t i = 0; (i) < ((kids).Length()); (++(i))) {
            DeallocPIndexedDBRequest(kids[i]);
        }
        (mManagedPIndexedDBRequestChild).Clear();
    }
}

void
PIndexedDBIndexChild::Write(
        const OptionalKeyRange& __v,
        Message* __msg)
{
    typedef OptionalKeyRange __type;
    Write(int((__v).type()), __msg);

    switch ((__v).type()) {
    case __type::TKeyRange:
        {
            Write((__v).get_KeyRange(), __msg);
            return;
        }
    case __type::Tvoid_t:
        {
            Write((__v).get_void_t(), __msg);
            return;
        }
    default:
        {
            NS_RUNTIMEABORT("unknown union type");
            return;
        }
    }
}

bool
PIndexedDBIndexChild::Read(
        OptionalKeyRange* __v,
        const Message* __msg,
        void** __iter)
{
    typedef OptionalKeyRange __type;
    int type;
    if ((!(Read((&(type)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }

    switch (type) {
    case __type::TKeyRange:
        {
            KeyRange tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_KeyRange())), __msg, __iter);
        }
    case __type::Tvoid_t:
        {
            void_t tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_void_t())), __msg, __iter);
        }
    default:
        {
            mozilla::ipc::ProtocolErrorBreakpoint("unknown union type");
            return false;
        }
    }
}

void
PIndexedDBIndexChild::Write(
        PIndexedDBCursorChild* __v,
        Message* __msg,
        bool __nullable)
{
    int32_t id;
    if ((!(__v))) {
        if ((!(__nullable))) {
            NS_RUNTIMEABORT("NULL actor value passed to non-nullable param");
        }
        id = 0;
    }
    else {
        id = (__v)->mId;
        if ((1) == (id)) {
            NS_RUNTIMEABORT("actor has been |delete|d");
        }
    }

    Write(id, __msg);
}

bool
PIndexedDBIndexChild::Read(
        PIndexedDBCursorChild** __v,
        const Message* __msg,
        void** __iter,
        bool __nullable)
{
    int32_t id;
    if ((!(Read((&(id)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if (((1) == (id)) || (((0) == (id)) && ((!(__nullable))))) {
        mozilla::ipc::ProtocolErrorBreakpoint("bad ID for PIndexedDBIndex");
        return false;
    }

    if ((0) == (id)) {
        (*(__v)) = 0;
        return true;
    }

    ChannelListener* listener = Lookup(id);
    if ((!(listener))) {
        mozilla::ipc::ProtocolErrorBreakpoint("could not look up PIndexedDBCursor");
        return false;
    }

    if ((PIndexedDBCursorMsgStart) != ((listener)->GetProtocolTypeId())) {
        mozilla::ipc::ProtocolErrorBreakpoint("actor that should be of type PIndexedDBCursor has different type");
        return false;
    }

    (*(__v)) = static_cast<PIndexedDBCursorChild*>(listener);
    return true;
}

void
PIndexedDBIndexChild::Write(
        const GetKeyParams& __v,
        Message* __msg)
{
    Write((__v).keyRange(), __msg);
}

bool
PIndexedDBIndexChild::Read(
        GetKeyParams* __v,
        const Message* __msg,
        void** __iter)
{
    if ((!(Read((&((__v)->keyRange())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    return true;
}

void
PIndexedDBIndexChild::Write(
        const IndexCursorConstructorParams& __v,
        Message* __msg)
{
    // skipping actor field that's meaningless on this side
    Write((__v).requestChild(), __msg, false);
    Write((__v).direction(), __msg);
    Write((__v).key(), __msg);
    Write((__v).objectKey(), __msg);
    Write((__v).optionalCloneInfo(), __msg);
    // skipping actor field that's meaningless on this side
    Write((__v).blobsChild(), __msg);
}

bool
PIndexedDBIndexChild::Read(
        IndexCursorConstructorParams* __v,
        const Message* __msg,
        void** __iter)
{
    // skipping actor field that's meaningless on this side
    if ((!(Read((&((__v)->requestChild())), __msg, __iter, false)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->direction())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->key())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->objectKey())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->optionalCloneInfo())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    // skipping actor field that's meaningless on this side
    if ((!(Read((&((__v)->blobsChild())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    return true;
}

void
PIndexedDBIndexChild::Write(
        const GetParams& __v,
        Message* __msg)
{
    Write((__v).keyRange(), __msg);
}

bool
PIndexedDBIndexChild::Read(
        GetParams* __v,
        const Message* __msg,
        void** __iter)
{
    if ((!(Read((&((__v)->keyRange())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    return true;
}

void
PIndexedDBIndexChild::Write(
        const KeyRange& __v,
        Message* __msg)
{
    Write((__v).lower(), __msg);
    Write((__v).upper(), __msg);
    Write((__v).lowerOpen(), __msg);
    Write((__v).upperOpen(), __msg);
    Write((__v).isOnly(), __msg);
}

bool
PIndexedDBIndexChild::Read(
        KeyRange* __v,
        const Message* __msg,
        void** __iter)
{
    if ((!(Read((&((__v)->lower())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->upper())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->lowerOpen())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->upperOpen())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->isOnly())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    return true;
}

void
PIndexedDBIndexChild::Write(
        const GetAllParams& __v,
        Message* __msg)
{
    Write((__v).optionalKeyRange(), __msg);
    Write((__v).limit(), __msg);
}

bool
PIndexedDBIndexChild::Read(
        GetAllParams* __v,
        const Message* __msg,
        void** __iter)
{
    if ((!(Read((&((__v)->optionalKeyRange())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->limit())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    return true;
}

void
PIndexedDBIndexChild::Write(
        const CountParams& __v,
        Message* __msg)
{
    Write((__v).optionalKeyRange(), __msg);
}

bool
PIndexedDBIndexChild::Read(
        CountParams* __v,
        const Message* __msg,
        void** __iter)
{
    if ((!(Read((&((__v)->optionalKeyRange())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    return true;
}

void
PIndexedDBIndexChild::Write(
        const InfallibleTArray<PBlobChild*>& __v,
        Message* __msg)
{
    uint32_t length = (__v).Length();
    Write(length, __msg);

    for (uint32_t i = 0; (i) < (length); (++(i))) {
        Write(__v[i], __msg, false);
    }
}

bool
PIndexedDBIndexChild::Read(
        InfallibleTArray<PBlobChild*>* __v,
        const Message* __msg,
        void** __iter)
{
    InfallibleTArray<PBlobChild*>& a = (*(__v));
    uint32_t length;
    if ((!(Read((&(length)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }

    (__v)->SetLength(length);
    for (uint32_t i = 0; (i) < (length); (++(i))) {
        if ((!(Read((&(a[i])), __msg, __iter, false)))) {
            mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
            return false;
        }
    }
    return true;
}

void
PIndexedDBIndexChild::Write(
        PIndexedDBRequestChild* __v,
        Message* __msg,
        bool __nullable)
{
    int32_t id;
    if ((!(__v))) {
        if ((!(__nullable))) {
            NS_RUNTIMEABORT("NULL actor value passed to non-nullable param");
        }
        id = 0;
    }
    else {
        id = (__v)->mId;
        if ((1) == (id)) {
            NS_RUNTIMEABORT("actor has been |delete|d");
        }
    }

    Write(id, __msg);
}

bool
PIndexedDBIndexChild::Read(
        PIndexedDBRequestChild** __v,
        const Message* __msg,
        void** __iter,
        bool __nullable)
{
    int32_t id;
    if ((!(Read((&(id)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if (((1) == (id)) || (((0) == (id)) && ((!(__nullable))))) {
        mozilla::ipc::ProtocolErrorBreakpoint("bad ID for PIndexedDBIndex");
        return false;
    }

    if ((0) == (id)) {
        (*(__v)) = 0;
        return true;
    }

    ChannelListener* listener = Lookup(id);
    if ((!(listener))) {
        mozilla::ipc::ProtocolErrorBreakpoint("could not look up PIndexedDBRequest");
        return false;
    }

    if ((PIndexedDBRequestMsgStart) != ((listener)->GetProtocolTypeId())) {
        mozilla::ipc::ProtocolErrorBreakpoint("actor that should be of type PIndexedDBRequest has different type");
        return false;
    }

    (*(__v)) = static_cast<PIndexedDBRequestChild*>(listener);
    return true;
}

void
PIndexedDBIndexChild::Write(
        PIndexedDBIndexChild* __v,
        Message* __msg,
        bool __nullable)
{
    int32_t id;
    if ((!(__v))) {
        if ((!(__nullable))) {
            NS_RUNTIMEABORT("NULL actor value passed to non-nullable param");
        }
        id = 0;
    }
    else {
        id = (__v)->mId;
        if ((1) == (id)) {
            NS_RUNTIMEABORT("actor has been |delete|d");
        }
    }

    Write(id, __msg);
}

bool
PIndexedDBIndexChild::Read(
        PIndexedDBIndexChild** __v,
        const Message* __msg,
        void** __iter,
        bool __nullable)
{
    int32_t id;
    if ((!(Read((&(id)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if (((1) == (id)) || (((0) == (id)) && ((!(__nullable))))) {
        mozilla::ipc::ProtocolErrorBreakpoint("bad ID for PIndexedDBIndex");
        return false;
    }

    if ((0) == (id)) {
        (*(__v)) = 0;
        return true;
    }

    ChannelListener* listener = Lookup(id);
    if ((!(listener))) {
        mozilla::ipc::ProtocolErrorBreakpoint("could not look up PIndexedDBIndex");
        return false;
    }

    if ((PIndexedDBIndexMsgStart) != ((listener)->GetProtocolTypeId())) {
        mozilla::ipc::ProtocolErrorBreakpoint("actor that should be of type PIndexedDBIndex has different type");
        return false;
    }

    (*(__v)) = static_cast<PIndexedDBIndexChild*>(listener);
    return true;
}

void
PIndexedDBIndexChild::Write(
        const IndexRequestParams& __v,
        Message* __msg)
{
    typedef IndexRequestParams __type;
    Write(int((__v).type()), __msg);

    switch ((__v).type()) {
    case __type::TGetParams:
        {
            Write((__v).get_GetParams(), __msg);
            return;
        }
    case __type::TGetKeyParams:
        {
            Write((__v).get_GetKeyParams(), __msg);
            return;
        }
    case __type::TGetAllParams:
        {
            Write((__v).get_GetAllParams(), __msg);
            return;
        }
    case __type::TGetAllKeysParams:
        {
            Write((__v).get_GetAllKeysParams(), __msg);
            return;
        }
    case __type::TCountParams:
        {
            Write((__v).get_CountParams(), __msg);
            return;
        }
    case __type::TOpenCursorParams:
        {
            Write((__v).get_OpenCursorParams(), __msg);
            return;
        }
    case __type::TOpenKeyCursorParams:
        {
            Write((__v).get_OpenKeyCursorParams(), __msg);
            return;
        }
    default:
        {
            NS_RUNTIMEABORT("unknown union type");
            return;
        }
    }
}

bool
PIndexedDBIndexChild::Read(
        IndexRequestParams* __v,
        const Message* __msg,
        void** __iter)
{
    typedef IndexRequestParams __type;
    int type;
    if ((!(Read((&(type)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }

    switch (type) {
    case __type::TGetParams:
        {
            GetParams tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_GetParams())), __msg, __iter);
        }
    case __type::TGetKeyParams:
        {
            GetKeyParams tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_GetKeyParams())), __msg, __iter);
        }
    case __type::TGetAllParams:
        {
            GetAllParams tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_GetAllParams())), __msg, __iter);
        }
    case __type::TGetAllKeysParams:
        {
            GetAllKeysParams tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_GetAllKeysParams())), __msg, __iter);
        }
    case __type::TCountParams:
        {
            CountParams tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_CountParams())), __msg, __iter);
        }
    case __type::TOpenCursorParams:
        {
            OpenCursorParams tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_OpenCursorParams())), __msg, __iter);
        }
    case __type::TOpenKeyCursorParams:
        {
            OpenKeyCursorParams tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_OpenKeyCursorParams())), __msg, __iter);
        }
    default:
        {
            mozilla::ipc::ProtocolErrorBreakpoint("unknown union type");
            return false;
        }
    }
}

void
PIndexedDBIndexChild::Write(
        PBlobChild* __v,
        Message* __msg,
        bool __nullable)
{
    int32_t id;
    if ((!(__v))) {
        if ((!(__nullable))) {
            NS_RUNTIMEABORT("NULL actor value passed to non-nullable param");
        }
        id = 0;
    }
    else {
        id = (__v)->mId;
        if ((1) == (id)) {
            NS_RUNTIMEABORT("actor has been |delete|d");
        }
    }

    Write(id, __msg);
}

bool
PIndexedDBIndexChild::Read(
        PBlobChild** __v,
        const Message* __msg,
        void** __iter,
        bool __nullable)
{
    int32_t id;
    if ((!(Read((&(id)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if (((1) == (id)) || (((0) == (id)) && ((!(__nullable))))) {
        mozilla::ipc::ProtocolErrorBreakpoint("bad ID for PIndexedDBIndex");
        return false;
    }

    if ((0) == (id)) {
        (*(__v)) = 0;
        return true;
    }

    ChannelListener* listener = Lookup(id);
    if ((!(listener))) {
        mozilla::ipc::ProtocolErrorBreakpoint("could not look up PBlob");
        return false;
    }

    if ((PBlobMsgStart) != ((listener)->GetProtocolTypeId())) {
        mozilla::ipc::ProtocolErrorBreakpoint("actor that should be of type PBlob has different type");
        return false;
    }

    (*(__v)) = static_cast<PBlobChild*>(listener);
    return true;
}

void
PIndexedDBIndexChild::Write(
        const OpenKeyCursorParams& __v,
        Message* __msg)
{
    Write((__v).optionalKeyRange(), __msg);
    Write((__v).direction(), __msg);
}

bool
PIndexedDBIndexChild::Read(
        OpenKeyCursorParams* __v,
        const Message* __msg,
        void** __iter)
{
    if ((!(Read((&((__v)->optionalKeyRange())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->direction())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    return true;
}

void
PIndexedDBIndexChild::Write(
        const GetAllKeysParams& __v,
        Message* __msg)
{
    Write((__v).optionalKeyRange(), __msg);
    Write((__v).limit(), __msg);
}

bool
PIndexedDBIndexChild::Read(
        GetAllKeysParams* __v,
        const Message* __msg,
        void** __iter)
{
    if ((!(Read((&((__v)->optionalKeyRange())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->limit())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    return true;
}

void
PIndexedDBIndexChild::Write(
        const OptionalStructuredCloneReadInfo& __v,
        Message* __msg)
{
    typedef OptionalStructuredCloneReadInfo __type;
    Write(int((__v).type()), __msg);

    switch ((__v).type()) {
    case __type::TSerializedStructuredCloneReadInfo:
        {
            Write((__v).get_SerializedStructuredCloneReadInfo(), __msg);
            return;
        }
    case __type::Tvoid_t:
        {
            Write((__v).get_void_t(), __msg);
            return;
        }
    default:
        {
            NS_RUNTIMEABORT("unknown union type");
            return;
        }
    }
}

bool
PIndexedDBIndexChild::Read(
        OptionalStructuredCloneReadInfo* __v,
        const Message* __msg,
        void** __iter)
{
    typedef OptionalStructuredCloneReadInfo __type;
    int type;
    if ((!(Read((&(type)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }

    switch (type) {
    case __type::TSerializedStructuredCloneReadInfo:
        {
            SerializedStructuredCloneReadInfo tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_SerializedStructuredCloneReadInfo())), __msg, __iter);
        }
    case __type::Tvoid_t:
        {
            void_t tmp;
            (*(__v)) = tmp;
            return Read((&((__v)->get_void_t())), __msg, __iter);
        }
    default:
        {
            mozilla::ipc::ProtocolErrorBreakpoint("unknown union type");
            return false;
        }
    }
}

void
PIndexedDBIndexChild::Write(
        const OpenCursorParams& __v,
        Message* __msg)
{
    Write((__v).optionalKeyRange(), __msg);
    Write((__v).direction(), __msg);
}

bool
PIndexedDBIndexChild::Read(
        OpenCursorParams* __v,
        const Message* __msg,
        void** __iter)
{
    if ((!(Read((&((__v)->optionalKeyRange())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if ((!(Read((&((__v)->direction())), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    return true;
}



} // namespace indexedDB
} // namespace dom
} // namespace mozilla
