//
// Automatically generated by ipdlc.
// Edit at your own risk
//


#include "mozilla/docshell/POfflineCacheUpdateChild.h"

#include "mozilla/dom/PBrowserChild.h"

typedef IPC::Message Message;
typedef mozilla::ipc::RPCChannel Channel;
typedef mozilla::ipc::RPCChannel::RPCListener ChannelListener;
typedef base::ProcessHandle ProcessHandle;
typedef mozilla::ipc::AsyncChannel AsyncChannel;
typedef mozilla::ipc::SharedMemory SharedMemory;
typedef mozilla::ipc::Trigger Trigger;
typedef mozilla::ipc::ActorHandle ActorHandle;
typedef mozilla::ipc::FileDescriptor FileDescriptor;
typedef mozilla::ipc::Shmem Shmem;
using mozilla::dom::PBrowserChild;

namespace mozilla {
namespace docshell {


void
POfflineCacheUpdateChild::ActorDestroy(ActorDestroyReason why)
{
}

POfflineCacheUpdateChild::POfflineCacheUpdateChild() :
    mId(0),
    mState(POfflineCacheUpdate::__Dead)
{
    MOZ_COUNT_CTOR(POfflineCacheUpdateChild);
}

POfflineCacheUpdateChild::~POfflineCacheUpdateChild()
{
    MOZ_COUNT_DTOR(POfflineCacheUpdateChild);
}

PBrowserChild*
POfflineCacheUpdateChild::Manager() const
{
    return static_cast<PBrowserChild*>(mManager);
}

POfflineCacheUpdate::State
POfflineCacheUpdateChild::state()
{
    return mState;
}

bool
POfflineCacheUpdateChild::Send__delete__(POfflineCacheUpdateChild* actor)
{
    if ((!(actor))) {
        return false;
    }

    if ((!(actor))) {
        return false;
    }

    POfflineCacheUpdate::Msg___delete__* __msg = new POfflineCacheUpdate::Msg___delete__();

    (actor)->Write(actor, __msg, false);

    (__msg)->set_routing_id((actor)->mId);


    if (mozilla::ipc::LoggingEnabled()) {
        (__msg)->Log("[POfflineCacheUpdateChild] Sending ", stderr);
    }
    if ((!(POfflineCacheUpdate::Transition((actor)->mState, Trigger(Trigger::Recv, POfflineCacheUpdate::Msg___delete____ID), (&((actor)->mState)))))) {
        NS_WARNING("bad state transition!");
    }

    bool __sendok = ((actor)->mChannel)->Send(__msg);

    (actor)->DestroySubtree(Deletion);
    (actor)->DeallocSubtree();
    ((actor)->mManager)->RemoveManagee(POfflineCacheUpdateMsgStart, actor);
    return __sendok;
}

int32_t
POfflineCacheUpdateChild::Register(ChannelListener* aRouted)
{
    return (mManager)->Register(aRouted);
}

int32_t
POfflineCacheUpdateChild::RegisterID(
        ChannelListener* aRouted,
        int32_t aId)
{
    return (mManager)->RegisterID(aRouted, aId);
}

ChannelListener*
POfflineCacheUpdateChild::Lookup(int32_t aId)
{
    return (mManager)->Lookup(aId);
}

void
POfflineCacheUpdateChild::Unregister(int32_t aId)
{
    return (mManager)->Unregister(aId);
}

void
POfflineCacheUpdateChild::RemoveManagee(
        int32_t aProtocolId,
        ChannelListener* aListener)
{
    NS_RUNTIMEABORT("unreached");
    return;
}

Shmem::SharedMemory*
POfflineCacheUpdateChild::CreateSharedMemory(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        bool aUnsafe,
        Shmem::id_t* aId)
{
    return (mManager)->CreateSharedMemory(aSize, aType, aUnsafe, aId);
}

bool
POfflineCacheUpdateChild::AdoptSharedMemory(
        Shmem::SharedMemory* segment,
        Shmem::id_t* aId)
{
    return (mManager)->AdoptSharedMemory(segment, aId);
}

Shmem::SharedMemory*
POfflineCacheUpdateChild::LookupSharedMemory(Shmem::id_t aId)
{
    return (mManager)->LookupSharedMemory(aId);
}

bool
POfflineCacheUpdateChild::IsTrackingSharedMemory(Shmem::SharedMemory* segment)
{
    return (mManager)->IsTrackingSharedMemory(segment);
}

bool
POfflineCacheUpdateChild::DestroySharedMemory(Shmem& shmem)
{
    return (mManager)->DestroySharedMemory(shmem);
}

ProcessHandle
POfflineCacheUpdateChild::OtherProcess() const
{
    return (mManager)->OtherProcess();
}

AsyncChannel*
POfflineCacheUpdateChild::GetIPCChannel()
{
    return mChannel;
}

POfflineCacheUpdateChild::Result
POfflineCacheUpdateChild::OnMessageReceived(const Message& __msg)
{
    switch ((__msg).type()) {
    case POfflineCacheUpdate::Reply___delete____ID:
        {
            return MsgProcessed;
        }
    case POfflineCacheUpdate::Msg_NotifyStateEvent__ID:
        {
            (const_cast<Message&>(__msg)).set_name("POfflineCacheUpdate::Msg_NotifyStateEvent");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const POfflineCacheUpdate::Msg_NotifyStateEvent*>((&(__msg))))->Log("[POfflineCacheUpdateChild] Received ", stderr);
            }

            void* __iter = 0;
            uint32_t stateEvent;
            uint64_t byteProgress;

            if ((!(Read((&(stateEvent)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            if ((!(Read((&(byteProgress)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            (__msg).EndRead(__iter);
            if ((!(POfflineCacheUpdate::Transition(mState, Trigger(Trigger::Send, POfflineCacheUpdate::Msg_NotifyStateEvent__ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            if ((!(RecvNotifyStateEvent(stateEvent, byteProgress)))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for NotifyStateEvent returned error code");
                return MsgProcessingError;
            }

            return MsgProcessed;
        }
    case POfflineCacheUpdate::Msg_AssociateDocuments__ID:
        {
            (const_cast<Message&>(__msg)).set_name("POfflineCacheUpdate::Msg_AssociateDocuments");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const POfflineCacheUpdate::Msg_AssociateDocuments*>((&(__msg))))->Log("[POfflineCacheUpdateChild] Received ", stderr);
            }

            void* __iter = 0;
            nsCString cacheGroupId;
            nsCString cacheClientId;

            if ((!(Read((&(cacheGroupId)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            if ((!(Read((&(cacheClientId)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            (__msg).EndRead(__iter);
            if ((!(POfflineCacheUpdate::Transition(mState, Trigger(Trigger::Send, POfflineCacheUpdate::Msg_AssociateDocuments__ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            if ((!(RecvAssociateDocuments(cacheGroupId, cacheClientId)))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for AssociateDocuments returned error code");
                return MsgProcessingError;
            }

            return MsgProcessed;
        }
    case POfflineCacheUpdate::Msg_Finish__ID:
        {
            (const_cast<Message&>(__msg)).set_name("POfflineCacheUpdate::Msg_Finish");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const POfflineCacheUpdate::Msg_Finish*>((&(__msg))))->Log("[POfflineCacheUpdateChild] Received ", stderr);
            }

            void* __iter = 0;
            bool succeded;
            bool isUpgrate;

            if ((!(Read((&(succeded)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            if ((!(Read((&(isUpgrate)), (&(__msg)), (&(__iter)))))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            (__msg).EndRead(__iter);
            if ((!(POfflineCacheUpdate::Transition(mState, Trigger(Trigger::Send, POfflineCacheUpdate::Msg_Finish__ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            if ((!(RecvFinish(succeded, isUpgrate)))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for Finish returned error code");
                return MsgProcessingError;
            }

            return MsgProcessed;
        }
    default:
        {
            return MsgNotKnown;
        }
    }
}

POfflineCacheUpdateChild::Result
POfflineCacheUpdateChild::OnMessageReceived(
        const Message& __msg,
        Message*& __reply)
{
    return MsgNotKnown;
}

POfflineCacheUpdateChild::Result
POfflineCacheUpdateChild::OnCallReceived(
        const Message& __msg,
        Message*& __reply)
{
    return MsgNotKnown;
}

void
POfflineCacheUpdateChild::OnProcessingError(Result code)
{
    NS_RUNTIMEABORT("`OnProcessingError' called on non-toplevel actor");
}

int32_t
POfflineCacheUpdateChild::GetProtocolTypeId()
{
    return POfflineCacheUpdateMsgStart;
}

bool
POfflineCacheUpdateChild::OnReplyTimeout()
{
    NS_RUNTIMEABORT("`OnReplyTimeout' called on non-toplevel actor");
    return false;
}

void
POfflineCacheUpdateChild::OnChannelClose()
{
    NS_RUNTIMEABORT("`OnClose' called on non-toplevel actor");
}

void
POfflineCacheUpdateChild::OnChannelError()
{
    NS_RUNTIMEABORT("`OnError' called on non-toplevel actor");
}

void
POfflineCacheUpdateChild::OnChannelConnected(int32_t pid)
{
    NS_RUNTIMEABORT("'OnConnected' called on non-toplevel actor");
}

bool
POfflineCacheUpdateChild::AllocShmem(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        Shmem* aMem)
{
    Shmem::id_t aId;
    nsAutoPtr<Shmem::SharedMemory> rawmem(CreateSharedMemory(aSize, aType, false, (&(aId))));
    if ((!(rawmem))) {
        return false;
    }

    (*(aMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), (rawmem).forget(), aId);
    return true;
}

bool
POfflineCacheUpdateChild::AllocUnsafeShmem(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        Shmem* aMem)
{
    Shmem::id_t aId;
    nsAutoPtr<Shmem::SharedMemory> rawmem(CreateSharedMemory(aSize, aType, true, (&(aId))));
    if ((!(rawmem))) {
        return false;
    }

    (*(aMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), (rawmem).forget(), aId);
    return true;
}

bool
POfflineCacheUpdateChild::AdoptShmem(
        Shmem& aMem,
        Shmem* aOutMem)
{
    Shmem::SharedMemory* rawmem = (aMem).Segment(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    if (((!(rawmem))) || (IsTrackingSharedMemory(rawmem))) {
        NS_RUNTIMEABORT("bad Shmem");
    }

    Shmem::id_t aId;
    if ((!(AdoptSharedMemory(rawmem, (&(aId)))))) {
        return false;
    }

    (*(aOutMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), rawmem, aId);
    return true;
}

bool
POfflineCacheUpdateChild::DeallocShmem(Shmem& aMem)
{
    bool ok = DestroySharedMemory(aMem);
    (aMem).forget(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    return ok;
}

void
POfflineCacheUpdateChild::FatalError(const char* const msg) const
{
    // Virtual method to prevent inlining.
    // This give us better error reporting.
    // See bug 589371

    NS_ERROR("IPDL error:");
    NS_ERROR(msg);
    mozilla::ipc::ProtocolErrorBreakpoint(msg);

    NS_RUNTIMEABORT("[POfflineCacheUpdateChild] abort()ing as a result");
}

void
POfflineCacheUpdateChild::DestroySubtree(ActorDestroyReason why)
{
    // Unregister from our manager.
    Unregister(mId);
    mId = 1;

    // Finally, destroy "us".
    ActorDestroy(why);
}

void
POfflineCacheUpdateChild::DeallocSubtree()
{
}

void
POfflineCacheUpdateChild::Write(
        POfflineCacheUpdateChild* __v,
        Message* __msg,
        bool __nullable)
{
    int32_t id;
    if ((!(__v))) {
        if ((!(__nullable))) {
            NS_RUNTIMEABORT("NULL actor value passed to non-nullable param");
        }
        id = 0;
    }
    else {
        id = (__v)->mId;
        if ((1) == (id)) {
            NS_RUNTIMEABORT("actor has been |delete|d");
        }
    }

    Write(id, __msg);
}

bool
POfflineCacheUpdateChild::Read(
        POfflineCacheUpdateChild** __v,
        const Message* __msg,
        void** __iter,
        bool __nullable)
{
    int32_t id;
    if ((!(Read((&(id)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if (((1) == (id)) || (((0) == (id)) && ((!(__nullable))))) {
        mozilla::ipc::ProtocolErrorBreakpoint("bad ID for POfflineCacheUpdate");
        return false;
    }

    if ((0) == (id)) {
        (*(__v)) = 0;
        return true;
    }

    ChannelListener* listener = Lookup(id);
    if ((!(listener))) {
        mozilla::ipc::ProtocolErrorBreakpoint("could not look up POfflineCacheUpdate");
        return false;
    }

    if ((POfflineCacheUpdateMsgStart) != ((listener)->GetProtocolTypeId())) {
        mozilla::ipc::ProtocolErrorBreakpoint("actor that should be of type POfflineCacheUpdate has different type");
        return false;
    }

    (*(__v)) = static_cast<POfflineCacheUpdateChild*>(listener);
    return true;
}



} // namespace docshell
} // namespace mozilla
