//
// Automatically generated by ipdlc.
// Edit at your own risk
//


#include "mozilla/plugins/PPluginBackgroundDestroyerChild.h"

#include "mozilla/plugins/PPluginInstanceChild.h"

typedef IPC::Message Message;
typedef mozilla::ipc::RPCChannel Channel;
typedef mozilla::ipc::RPCChannel::RPCListener ChannelListener;
typedef base::ProcessHandle ProcessHandle;
typedef mozilla::ipc::AsyncChannel AsyncChannel;
typedef mozilla::ipc::SharedMemory SharedMemory;
typedef mozilla::ipc::Trigger Trigger;
typedef mozilla::ipc::ActorHandle ActorHandle;
typedef mozilla::ipc::FileDescriptor FileDescriptor;
typedef mozilla::ipc::Shmem Shmem;
using mozilla::plugins::PPluginInstanceChild;

namespace mozilla {
namespace plugins {


void
PPluginBackgroundDestroyerChild::ActorDestroy(ActorDestroyReason why)
{
}

PPluginBackgroundDestroyerChild::PPluginBackgroundDestroyerChild() :
    mId(0),
    mState(PPluginBackgroundDestroyer::__Dead)
{
    MOZ_COUNT_CTOR(PPluginBackgroundDestroyerChild);
}

PPluginBackgroundDestroyerChild::~PPluginBackgroundDestroyerChild()
{
    MOZ_COUNT_DTOR(PPluginBackgroundDestroyerChild);
}

PPluginInstanceChild*
PPluginBackgroundDestroyerChild::Manager() const
{
    return static_cast<PPluginInstanceChild*>(mManager);
}

PPluginBackgroundDestroyer::State
PPluginBackgroundDestroyerChild::state()
{
    return mState;
}

bool
PPluginBackgroundDestroyerChild::Send__delete__(PPluginBackgroundDestroyerChild* actor)
{
    if ((!(actor))) {
        return false;
    }

    if ((!(actor))) {
        return false;
    }

    PPluginBackgroundDestroyer::Msg___delete__* __msg = new PPluginBackgroundDestroyer::Msg___delete__();

    (actor)->Write(actor, __msg, false);

    (__msg)->set_routing_id((actor)->mId);


    if (mozilla::ipc::LoggingEnabled()) {
        (__msg)->Log("[PPluginBackgroundDestroyerChild] Sending ", stderr);
    }
    if ((!(PPluginBackgroundDestroyer::Transition((actor)->mState, Trigger(Trigger::Recv, PPluginBackgroundDestroyer::Msg___delete____ID), (&((actor)->mState)))))) {
        NS_WARNING("bad state transition!");
    }

    bool __sendok = ((actor)->mChannel)->Send(__msg);

    (actor)->DestroySubtree(Deletion);
    (actor)->DeallocSubtree();
    ((actor)->mManager)->RemoveManagee(PPluginBackgroundDestroyerMsgStart, actor);
    return __sendok;
}

int32_t
PPluginBackgroundDestroyerChild::Register(ChannelListener* aRouted)
{
    return (mManager)->Register(aRouted);
}

int32_t
PPluginBackgroundDestroyerChild::RegisterID(
        ChannelListener* aRouted,
        int32_t aId)
{
    return (mManager)->RegisterID(aRouted, aId);
}

ChannelListener*
PPluginBackgroundDestroyerChild::Lookup(int32_t aId)
{
    return (mManager)->Lookup(aId);
}

void
PPluginBackgroundDestroyerChild::Unregister(int32_t aId)
{
    return (mManager)->Unregister(aId);
}

void
PPluginBackgroundDestroyerChild::RemoveManagee(
        int32_t aProtocolId,
        ChannelListener* aListener)
{
    NS_RUNTIMEABORT("unreached");
    return;
}

Shmem::SharedMemory*
PPluginBackgroundDestroyerChild::CreateSharedMemory(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        bool aUnsafe,
        Shmem::id_t* aId)
{
    return (mManager)->CreateSharedMemory(aSize, aType, aUnsafe, aId);
}

bool
PPluginBackgroundDestroyerChild::AdoptSharedMemory(
        Shmem::SharedMemory* segment,
        Shmem::id_t* aId)
{
    return (mManager)->AdoptSharedMemory(segment, aId);
}

Shmem::SharedMemory*
PPluginBackgroundDestroyerChild::LookupSharedMemory(Shmem::id_t aId)
{
    return (mManager)->LookupSharedMemory(aId);
}

bool
PPluginBackgroundDestroyerChild::IsTrackingSharedMemory(Shmem::SharedMemory* segment)
{
    return (mManager)->IsTrackingSharedMemory(segment);
}

bool
PPluginBackgroundDestroyerChild::DestroySharedMemory(Shmem& shmem)
{
    return (mManager)->DestroySharedMemory(shmem);
}

ProcessHandle
PPluginBackgroundDestroyerChild::OtherProcess() const
{
    return (mManager)->OtherProcess();
}

AsyncChannel*
PPluginBackgroundDestroyerChild::GetIPCChannel()
{
    return mChannel;
}

PPluginBackgroundDestroyerChild::Result
PPluginBackgroundDestroyerChild::OnMessageReceived(const Message& __msg)
{
    switch ((__msg).type()) {
    case PPluginBackgroundDestroyer::Reply___delete____ID:
        {
            return MsgProcessed;
        }
    default:
        {
            return MsgNotKnown;
        }
    }
}

PPluginBackgroundDestroyerChild::Result
PPluginBackgroundDestroyerChild::OnMessageReceived(
        const Message& __msg,
        Message*& __reply)
{
    return MsgNotKnown;
}

PPluginBackgroundDestroyerChild::Result
PPluginBackgroundDestroyerChild::OnCallReceived(
        const Message& __msg,
        Message*& __reply)
{
    return MsgNotKnown;
}

void
PPluginBackgroundDestroyerChild::OnProcessingError(Result code)
{
    NS_RUNTIMEABORT("`OnProcessingError' called on non-toplevel actor");
}

int32_t
PPluginBackgroundDestroyerChild::GetProtocolTypeId()
{
    return PPluginBackgroundDestroyerMsgStart;
}

bool
PPluginBackgroundDestroyerChild::OnReplyTimeout()
{
    NS_RUNTIMEABORT("`OnReplyTimeout' called on non-toplevel actor");
    return false;
}

void
PPluginBackgroundDestroyerChild::OnChannelClose()
{
    NS_RUNTIMEABORT("`OnClose' called on non-toplevel actor");
}

void
PPluginBackgroundDestroyerChild::OnChannelError()
{
    NS_RUNTIMEABORT("`OnError' called on non-toplevel actor");
}

void
PPluginBackgroundDestroyerChild::OnChannelConnected(int32_t pid)
{
    NS_RUNTIMEABORT("'OnConnected' called on non-toplevel actor");
}

bool
PPluginBackgroundDestroyerChild::AllocShmem(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        Shmem* aMem)
{
    Shmem::id_t aId;
    nsAutoPtr<Shmem::SharedMemory> rawmem(CreateSharedMemory(aSize, aType, false, (&(aId))));
    if ((!(rawmem))) {
        return false;
    }

    (*(aMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), (rawmem).forget(), aId);
    return true;
}

bool
PPluginBackgroundDestroyerChild::AllocUnsafeShmem(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        Shmem* aMem)
{
    Shmem::id_t aId;
    nsAutoPtr<Shmem::SharedMemory> rawmem(CreateSharedMemory(aSize, aType, true, (&(aId))));
    if ((!(rawmem))) {
        return false;
    }

    (*(aMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), (rawmem).forget(), aId);
    return true;
}

bool
PPluginBackgroundDestroyerChild::AdoptShmem(
        Shmem& aMem,
        Shmem* aOutMem)
{
    Shmem::SharedMemory* rawmem = (aMem).Segment(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    if (((!(rawmem))) || (IsTrackingSharedMemory(rawmem))) {
        NS_RUNTIMEABORT("bad Shmem");
    }

    Shmem::id_t aId;
    if ((!(AdoptSharedMemory(rawmem, (&(aId)))))) {
        return false;
    }

    (*(aOutMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), rawmem, aId);
    return true;
}

bool
PPluginBackgroundDestroyerChild::DeallocShmem(Shmem& aMem)
{
    bool ok = DestroySharedMemory(aMem);
    (aMem).forget(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    return ok;
}

void
PPluginBackgroundDestroyerChild::FatalError(const char* const msg) const
{
    // Virtual method to prevent inlining.
    // This give us better error reporting.
    // See bug 589371

    NS_ERROR("IPDL error:");
    NS_ERROR(msg);
    mozilla::ipc::ProtocolErrorBreakpoint(msg);

    NS_RUNTIMEABORT("[PPluginBackgroundDestroyerChild] abort()ing as a result");
}

void
PPluginBackgroundDestroyerChild::DestroySubtree(ActorDestroyReason why)
{
    // Unregister from our manager.
    Unregister(mId);
    mId = 1;

    // Finally, destroy "us".
    ActorDestroy(why);
}

void
PPluginBackgroundDestroyerChild::DeallocSubtree()
{
}

void
PPluginBackgroundDestroyerChild::Write(
        PPluginBackgroundDestroyerChild* __v,
        Message* __msg,
        bool __nullable)
{
    int32_t id;
    if ((!(__v))) {
        if ((!(__nullable))) {
            NS_RUNTIMEABORT("NULL actor value passed to non-nullable param");
        }
        id = 0;
    }
    else {
        id = (__v)->mId;
        if ((1) == (id)) {
            NS_RUNTIMEABORT("actor has been |delete|d");
        }
    }

    Write(id, __msg);
}

bool
PPluginBackgroundDestroyerChild::Read(
        PPluginBackgroundDestroyerChild** __v,
        const Message* __msg,
        void** __iter,
        bool __nullable)
{
    int32_t id;
    if ((!(Read((&(id)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if (((1) == (id)) || (((0) == (id)) && ((!(__nullable))))) {
        mozilla::ipc::ProtocolErrorBreakpoint("bad ID for PPluginBackgroundDestroyer");
        return false;
    }

    if ((0) == (id)) {
        (*(__v)) = 0;
        return true;
    }

    ChannelListener* listener = Lookup(id);
    if ((!(listener))) {
        mozilla::ipc::ProtocolErrorBreakpoint("could not look up PPluginBackgroundDestroyer");
        return false;
    }

    if ((PPluginBackgroundDestroyerMsgStart) != ((listener)->GetProtocolTypeId())) {
        mozilla::ipc::ProtocolErrorBreakpoint("actor that should be of type PPluginBackgroundDestroyer has different type");
        return false;
    }

    (*(__v)) = static_cast<PPluginBackgroundDestroyerChild*>(listener);
    return true;
}



} // namespace plugins
} // namespace mozilla
