//
// Automatically generated by ipdlc.
// Edit at your own risk
//


#include "mozilla/net/PRemoteOpenFileParent.h"

#include "mozilla/net/PNeckoParent.h"

typedef IPC::Message Message;
typedef mozilla::ipc::RPCChannel Channel;
typedef mozilla::ipc::RPCChannel::RPCListener ChannelListener;
typedef base::ProcessHandle ProcessHandle;
typedef mozilla::ipc::AsyncChannel AsyncChannel;
typedef mozilla::ipc::SharedMemory SharedMemory;
typedef mozilla::ipc::Trigger Trigger;
typedef mozilla::ipc::ActorHandle ActorHandle;
typedef mozilla::ipc::FileDescriptor FileDescriptor;
typedef mozilla::ipc::Shmem Shmem;
using mozilla::net::PNeckoParent;

namespace mozilla {
namespace net {


bool
PRemoteOpenFileParent::Recv__delete__()
{
    return true;
}

void
PRemoteOpenFileParent::ActorDestroy(ActorDestroyReason why)
{
}

PRemoteOpenFileParent::PRemoteOpenFileParent() :
    mId(0),
    mState(PRemoteOpenFile::__Dead)
{
    MOZ_COUNT_CTOR(PRemoteOpenFileParent);
}

PRemoteOpenFileParent::~PRemoteOpenFileParent()
{
    MOZ_COUNT_DTOR(PRemoteOpenFileParent);
}

PNeckoParent*
PRemoteOpenFileParent::Manager() const
{
    return static_cast<PNeckoParent*>(mManager);
}

PRemoteOpenFile::State
PRemoteOpenFileParent::state()
{
    return mState;
}

bool
PRemoteOpenFileParent::SendFileOpened(
        const FileDescriptor& fd,
        const nsresult& rv)
{
    PRemoteOpenFile::Msg_FileOpened* __msg = new PRemoteOpenFile::Msg_FileOpened();

    Write(fd, __msg);
    Write(rv, __msg);

    (__msg)->set_routing_id(mId);



    if (mozilla::ipc::LoggingEnabled()) {
        (__msg)->Log("[PRemoteOpenFileParent] Sending ", stderr);
    }
    if ((!(PRemoteOpenFile::Transition(mState, Trigger(Trigger::Send, PRemoteOpenFile::Msg_FileOpened__ID), (&(mState)))))) {
        NS_WARNING("bad state transition!");
    }

    bool __sendok = (mChannel)->Send(__msg);
    return __sendok;
}

int32_t
PRemoteOpenFileParent::Register(ChannelListener* aRouted)
{
    return (mManager)->Register(aRouted);
}

int32_t
PRemoteOpenFileParent::RegisterID(
        ChannelListener* aRouted,
        int32_t aId)
{
    return (mManager)->RegisterID(aRouted, aId);
}

ChannelListener*
PRemoteOpenFileParent::Lookup(int32_t aId)
{
    return (mManager)->Lookup(aId);
}

void
PRemoteOpenFileParent::Unregister(int32_t aId)
{
    return (mManager)->Unregister(aId);
}

void
PRemoteOpenFileParent::RemoveManagee(
        int32_t aProtocolId,
        ChannelListener* aListener)
{
    NS_RUNTIMEABORT("unreached");
    return;
}

Shmem::SharedMemory*
PRemoteOpenFileParent::CreateSharedMemory(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        bool aUnsafe,
        Shmem::id_t* aId)
{
    return (mManager)->CreateSharedMemory(aSize, aType, aUnsafe, aId);
}

bool
PRemoteOpenFileParent::AdoptSharedMemory(
        Shmem::SharedMemory* segment,
        Shmem::id_t* aId)
{
    return (mManager)->AdoptSharedMemory(segment, aId);
}

Shmem::SharedMemory*
PRemoteOpenFileParent::LookupSharedMemory(Shmem::id_t aId)
{
    return (mManager)->LookupSharedMemory(aId);
}

bool
PRemoteOpenFileParent::IsTrackingSharedMemory(Shmem::SharedMemory* segment)
{
    return (mManager)->IsTrackingSharedMemory(segment);
}

bool
PRemoteOpenFileParent::DestroySharedMemory(Shmem& shmem)
{
    return (mManager)->DestroySharedMemory(shmem);
}

ProcessHandle
PRemoteOpenFileParent::OtherProcess() const
{
    return (mManager)->OtherProcess();
}

AsyncChannel*
PRemoteOpenFileParent::GetIPCChannel()
{
    return mChannel;
}

PRemoteOpenFileParent::Result
PRemoteOpenFileParent::OnMessageReceived(const Message& __msg)
{
    switch ((__msg).type()) {
    case PRemoteOpenFile::Msg_AsyncOpenFile__ID:
        {
            (const_cast<Message&>(__msg)).set_name("PRemoteOpenFile::Msg_AsyncOpenFile");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PRemoteOpenFile::Msg_AsyncOpenFile*>((&(__msg))))->Log("[PRemoteOpenFileParent] Received ", stderr);
            }

            if ((!(PRemoteOpenFile::Transition(mState, Trigger(Trigger::Recv, PRemoteOpenFile::Msg_AsyncOpenFile__ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            if ((!(RecvAsyncOpenFile()))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for AsyncOpenFile returned error code");
                return MsgProcessingError;
            }

            return MsgProcessed;
        }
    case PRemoteOpenFile::Msg___delete____ID:
        {
            (const_cast<Message&>(__msg)).set_name("PRemoteOpenFile::Msg___delete__");
            if (mozilla::ipc::LoggingEnabled()) {
                (static_cast<const PRemoteOpenFile::Msg___delete__*>((&(__msg))))->Log("[PRemoteOpenFileParent] Received ", stderr);
            }

            void* __iter = 0;
            PRemoteOpenFileParent* actor;

            if ((!(Read((&(actor)), (&(__msg)), (&(__iter)), false)))) {
                FatalError("error deserializing (better message TODO)");
                return MsgValueError;
            }
            (__msg).EndRead(__iter);
            if ((!(PRemoteOpenFile::Transition(mState, Trigger(Trigger::Recv, PRemoteOpenFile::Msg___delete____ID), (&(mState)))))) {
                NS_WARNING("bad state transition!");
            }
            if ((!(Recv__delete__()))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler for __delete__ returned error code");
                return MsgProcessingError;
            }

            (actor)->DestroySubtree(Deletion);
            (actor)->DeallocSubtree();
            ((actor)->mManager)->RemoveManagee(PRemoteOpenFileMsgStart, actor);


            return MsgProcessed;
        }
    default:
        {
            return MsgNotKnown;
        }
    }
}

PRemoteOpenFileParent::Result
PRemoteOpenFileParent::OnMessageReceived(
        const Message& __msg,
        Message*& __reply)
{
    return MsgNotKnown;
}

PRemoteOpenFileParent::Result
PRemoteOpenFileParent::OnCallReceived(
        const Message& __msg,
        Message*& __reply)
{
    return MsgNotKnown;
}

void
PRemoteOpenFileParent::OnProcessingError(Result code)
{
    NS_RUNTIMEABORT("`OnProcessingError' called on non-toplevel actor");
}

int32_t
PRemoteOpenFileParent::GetProtocolTypeId()
{
    return PRemoteOpenFileMsgStart;
}

bool
PRemoteOpenFileParent::OnReplyTimeout()
{
    NS_RUNTIMEABORT("`OnReplyTimeout' called on non-toplevel actor");
    return false;
}

void
PRemoteOpenFileParent::OnChannelClose()
{
    NS_RUNTIMEABORT("`OnClose' called on non-toplevel actor");
}

void
PRemoteOpenFileParent::OnChannelError()
{
    NS_RUNTIMEABORT("`OnError' called on non-toplevel actor");
}

void
PRemoteOpenFileParent::OnChannelConnected(int32_t pid)
{
    NS_RUNTIMEABORT("'OnConnected' called on non-toplevel actor");
}

bool
PRemoteOpenFileParent::AllocShmem(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        Shmem* aMem)
{
    Shmem::id_t aId;
    nsAutoPtr<Shmem::SharedMemory> rawmem(CreateSharedMemory(aSize, aType, false, (&(aId))));
    if ((!(rawmem))) {
        return false;
    }

    (*(aMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), (rawmem).forget(), aId);
    return true;
}

bool
PRemoteOpenFileParent::AllocUnsafeShmem(
        size_t aSize,
        Shmem::SharedMemory::SharedMemoryType aType,
        Shmem* aMem)
{
    Shmem::id_t aId;
    nsAutoPtr<Shmem::SharedMemory> rawmem(CreateSharedMemory(aSize, aType, true, (&(aId))));
    if ((!(rawmem))) {
        return false;
    }

    (*(aMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), (rawmem).forget(), aId);
    return true;
}

bool
PRemoteOpenFileParent::AdoptShmem(
        Shmem& aMem,
        Shmem* aOutMem)
{
    Shmem::SharedMemory* rawmem = (aMem).Segment(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    if (((!(rawmem))) || (IsTrackingSharedMemory(rawmem))) {
        NS_RUNTIMEABORT("bad Shmem");
    }

    Shmem::id_t aId;
    if ((!(AdoptSharedMemory(rawmem, (&(aId)))))) {
        return false;
    }

    (*(aOutMem)) = Shmem(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead(), rawmem, aId);
    return true;
}

bool
PRemoteOpenFileParent::DeallocShmem(Shmem& aMem)
{
    bool ok = DestroySharedMemory(aMem);
    (aMem).forget(Shmem::IHadBetterBeIPDLCodeCallingThis_OtherwiseIAmADoodyhead());
    return ok;
}

void
PRemoteOpenFileParent::FatalError(const char* const msg) const
{
    // Virtual method to prevent inlining.
    // This give us better error reporting.
    // See bug 589371

    NS_ERROR("IPDL error:");
    NS_ERROR(msg);
    mozilla::ipc::ProtocolErrorBreakpoint(msg);

    NS_ERROR("[PRemoteOpenFileParent] killing child side as a result");

    if ((!(base::KillProcess(OtherProcess(), base::PROCESS_END_KILLED_BY_USER, false)))) {
        NS_ERROR("  may have failed to kill child!");
    }
}

void
PRemoteOpenFileParent::DestroySubtree(ActorDestroyReason why)
{
    // Unregister from our manager.
    Unregister(mId);
    mId = 1;

    // Finally, destroy "us".
    ActorDestroy(why);
}

void
PRemoteOpenFileParent::DeallocSubtree()
{
}

void
PRemoteOpenFileParent::Write(
        PRemoteOpenFileParent* __v,
        Message* __msg,
        bool __nullable)
{
    int32_t id;
    if ((!(__v))) {
        if ((!(__nullable))) {
            NS_RUNTIMEABORT("NULL actor value passed to non-nullable param");
        }
        id = 0;
    }
    else {
        id = (__v)->mId;
        if ((1) == (id)) {
            NS_RUNTIMEABORT("actor has been |delete|d");
        }
    }

    Write(id, __msg);
}

bool
PRemoteOpenFileParent::Read(
        PRemoteOpenFileParent** __v,
        const Message* __msg,
        void** __iter,
        bool __nullable)
{
    int32_t id;
    if ((!(Read((&(id)), __msg, __iter)))) {
        mozilla::ipc::ProtocolErrorBreakpoint("error deserializing (better message TODO)");
        return false;
    }
    if (((1) == (id)) || (((0) == (id)) && ((!(__nullable))))) {
        mozilla::ipc::ProtocolErrorBreakpoint("bad ID for PRemoteOpenFile");
        return false;
    }

    if ((0) == (id)) {
        (*(__v)) = 0;
        return true;
    }

    ChannelListener* listener = Lookup(id);
    if ((!(listener))) {
        mozilla::ipc::ProtocolErrorBreakpoint("could not look up PRemoteOpenFile");
        return false;
    }

    if ((PRemoteOpenFileMsgStart) != ((listener)->GetProtocolTypeId())) {
        mozilla::ipc::ProtocolErrorBreakpoint("actor that should be of type PRemoteOpenFile has different type");
        return false;
    }

    (*(__v)) = static_cast<PRemoteOpenFileParent*>(listener);
    return true;
}

void
PRemoteOpenFileParent::Write(
        const FileDescriptor& __v,
        Message* __msg)
{
    FileDescriptor::PickleType pfd = (__v).ShareTo(FileDescriptor::IPDLPrivate(), OtherProcess());
    IPC::WriteParam(__msg, pfd);
}

bool
PRemoteOpenFileParent::Read(
        FileDescriptor* __v,
        const Message* __msg,
        void** __iter)
{
    FileDescriptor::PickleType pfd;
    if ((!(IPC::ReadParam(__msg, __iter, (&(pfd)))))) {
        return false;
    }

    FileDescriptor fd = FileDescriptor(FileDescriptor::IPDLPrivate(), pfd);
    if ((!((fd).IsValid()))) {
        return false;
    }

    (*(__v)) = fd;
    return true;
}



} // namespace net
} // namespace mozilla
