#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/accessible/tests/mochitest/name
VPATH		= /home/txema/work/firefox-20.0+build1/accessible/tests/mochitest/name
relativesrcdir  = accessible/name

include $(DEPTH)/config/autoconf.mk

MOCHITEST_A11Y_FILES =\
		general.css \
		general.xbl \
		markup.js \
		test_button.html \
		test_general.html \
		test_general.xul \
		test_link.html \
		test_list.html \
		test_markup.html \
		test_svg.html \
		test_browserui.xul \
		test_tree.xul \
		markuprules.xml \
		$(NULL)

include $(topsrcdir)/config/rules.mk
