#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH          = ../../../../..
topsrcdir      = /home/txema/work/firefox-20.0+build1
srcdir         = /home/txema/work/firefox-20.0+build1/content/html/content/test/bug649134
VPATH          = /home/txema/work/firefox-20.0+build1/content/html/content/test/bug649134
relativesrcdir = content/html/content/test/bug649134

include $(DEPTH)/config/autoconf.mk

MOCHITEST_FILES = file_bug649134-1.sjs file_bug649134-2.sjs index.html

include $(topsrcdir)/config/rules.mk
