#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH     = ../../../../..
topsrcdir = /home/txema/work/firefox-20.0+build1
srcdir    = /home/txema/work/firefox-20.0+build1/dom/plugins/test/testplugin/secondplugin
VPATH     = /home/txema/work/firefox-20.0+build1/dom/plugins/test/testplugin/secondplugin

include $(DEPTH)/config/autoconf.mk

MODULE       = npsecondtest
LIBRARY_NAME = npsecondtest
MODULE_NAME  = SecondTestPlugin

RELATIVE_PATH=..
COCOA_NAME=SecondTest
include /home/txema/work/firefox-20.0+build1/dom/plugins/test/testplugin/secondplugin/../testplugin.mk
