#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/toolkit/components/places/tests/mochitest/bug_461710
VPATH		= /home/txema/work/firefox-20.0+build1/toolkit/components/places/tests/mochitest/bug_461710
relativesrcdir = toolkit/components/places/tests/bug_461710

include $(DEPTH)/config/autoconf.mk

MOCHITEST_FILES	= \
		visited_page.html \
		link_page.html \
		link_page-2.html \
		link_page-3.html \
		iframe.html \
		$(NULL)

include $(topsrcdir)/config/rules.mk
