#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


DEPTH     = ../../../..
topsrcdir = /home/txema/work/firefox-20.0+build1
srcdir    = /home/txema/work/firefox-20.0+build1/toolkit/components/viewsource/test
VPATH     = /home/txema/work/firefox-20.0+build1/toolkit/components/viewsource/test
relativesrcdir  = toolkit/components/viewsource/test

include $(DEPTH)/config/autoconf.mk

DIRS = browser


MOCHITEST_CHROME_FILES   = \
                test_428653.xul \
                $(NULL)

include $(topsrcdir)/config/rules.mk
