# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/orientation
VPATH		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/orientation
relativesrcdir	= dom/tests/mochitest/orientation

include $(DEPTH)/config/autoconf.mk

MOCHITEST_FILES	= \
		bug507902-frame.html \
		test_bug507902.html \
		$(NULL)

include $(topsrcdir)/config/rules.mk
