# Any copyright is dedicated to the Public Domain.
# http://creativecommons.org/publicdomain/zero/1.0/

DEPTH     = ../../../..
topsrcdir = /home/txema/work/firefox-20.0+build1
srcdir    = /home/txema/work/firefox-20.0+build1/browser/components/downloads/test
VPATH     = /home/txema/work/firefox-20.0+build1/browser/components/downloads/test

relativesrcdir = browser/components/downloads/test

include $(DEPTH)/config/autoconf.mk

XPCSHELL_TESTS = unit

DIRS = browser

include $(topsrcdir)/config/rules.mk
