#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

DEPTH		= ../../../../../../../..
topsrcdir	= /home/txema/work/firefox-20.0+build1
srcdir		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/prototype/test/unit/fixtures
VPATH		= /home/txema/work/firefox-20.0+build1/dom/tests/mochitest/ajax/prototype/test/unit/fixtures
relativesrcdir	= dom/tests/mochitest/ajax/prototype/test/unit/fixtures

include $(DEPTH)/config/autoconf.mk

MOCHITEST_FILES= \
	ajax.html \
	ajax.js \
	array.html \
	base.html \
	base.js \
	content.html \
	data.json \
	dom.css \
	dom.html \
	dom.js \
	element_mixins.html \
	element_mixins.js \
	empty.html \
	empty.js \
	enumerable.html \
	enumerable.js \
	event.html \
	form.html \
	hash.js \
	hello.js \
	logo.gif \
	position.html \
	selector.html \
	string.js \
	unittest.html \
	$(NULL)

include $(topsrcdir)/config/rules.mk
